export interface ClothingPose {
  id: string;
  name: string;
  prompt: string;
}

export const CLOTHING_POSES: ClothingPose[] = [
  { id: '01', name: '正面自然站姿', prompt: 'full body front standing pose, model facing camera, relaxed shoulders, arms naturally down, one leg slightly forward, subtle body curve, clean ecommerce knitwear pose, clothing clearly visible, realistic posture, minimal studio fashion pose' },
  { id: '02', name: '正面微扭腰站姿', prompt: 'front pose with slight waist twist, upper body facing camera, hips slightly angled, one knee softly bent, natural feminine curve, flattering slim silhouette, ecommerce sweater display pose' },
  { id: '03', name: '单手插裤袋', prompt: 'one hand casually inside jeans pocket, other arm relaxed, slight hip tilt, natural standing balance, effortless fashion attitude, showing knitwear front clearly, realistic commercial model pose' },
  { id: '04', name: '双手插裤袋', prompt: 'both hands partially tucked into front jeans pockets, relaxed elbows, shoulders down, casual confident pose, emphasizing waistline and sweater fit, clean SHEIN style ecommerce pose' },
  { id: '05', name: '一手插兜一手垂放', prompt: 'one hand in pocket, the other hand naturally hanging down, slight body lean, long leg emphasis, casual knitwear catalog pose, realistic relaxed standing posture' },
  { id: '06', name: '轻拉衣角', prompt: 'one hand gently holding sweater hem, slight fabric pull, showing knit texture and elasticity, relaxed fingers, natural tension on knit fabric, commercial apparel detail pose' },
  { id: '07', name: '双手拉衣摆', prompt: 'both hands lightly holding sweater hem, gently stretching the knit fabric, showing garment width and drape, relaxed shoulders, front fit clearly visible, realistic ecommerce clothing pose' },
  { id: '08', name: '单手整理衣领', prompt: 'one hand adjusting sweater collar, elbow naturally bent, realistic sleeve wrinkles, showing neckline detail, soft feminine gesture, clean commercial knitwear photography pose' },
  { id: '09', name: '双手整理开衫门襟', prompt: 'both hands lightly holding cardigan front opening, showing inner layer and button placket, natural finger placement, realistic knit folds, ecommerce cardigan display pose' },
  { id: '10', name: '单手扶纽扣', prompt: 'one hand touching cardigan button area, fingers gently placed near buttons, emphasizing front closure detail, relaxed upper body, realistic knitwear texture display pose' },
  { id: '11', name: '开衫半敞展示', prompt: 'cardigan worn open, one hand lightly holding one side of the cardigan, inner crop top visible, relaxed casual pose, showing cardigan structure and drape, SHEIN style knitwear pose' },
  { id: '12', name: '单肩微露开衫姿势', prompt: 'oversized cardigan slightly off one shoulder, one hand on waist, relaxed feminine pose, natural shoulder line, cozy knitwear styling, realistic ecommerce fashion pose' },
  { id: '13', name: '袖口遮手', prompt: 'long sweater sleeves partially covering hands, fingers slightly visible, cozy oversized knitwear feeling, relaxed arms, soft feminine posture, realistic winter sweater pose' },
  { id: '14', name: '单手抬起遮脸', prompt: 'one hand raised near face, sleeve partly covering hand, face partially hidden, casual mirror selfie inspired pose, cozy cardigan styling, realistic commercial fashion posture' },
  { id: '15', name: '单手摸头发', prompt: 'one hand naturally touching hair, elbow softly bent, relaxed shoulders, gentle feminine movement, sweater front still visible, clean ecommerce fashion pose' },
  { id: '16', name: '双手自然放前', prompt: 'both hands relaxed in front of body, wrists softly crossed near waist, modest feminine posture, clean front garment display, realistic knitwear catalog pose' },
  { id: '17', name: '手腕交叠站姿', prompt: 'hands loosely crossed at lower waist, relaxed fingers, shoulders soft, calm commercial expression, sweater silhouette clearly visible, elegant ecommerce pose' },
  { id: '18', name: '抱臂轻环抱', prompt: 'arms loosely crossed, not hiding garment too much, soft cozy sweater feeling, relaxed shoulders, natural upper body compression on knit fabric, realistic casual knitwear pose' },
  { id: '19', name: '一手抱臂一手摸袖口', prompt: 'one arm loosely across body, other hand touching sleeve cuff, showing ribbed cuff detail, cozy fashion gesture, realistic knitwear texture pose' },
  { id: '20', name: '手扶腰侧', prompt: 'one hand resting on waist, slight hip angle, other arm relaxed, emphasizing waistline and garment fit, natural confident ecommerce model pose' },
  { id: '21', name: '双手扶腰', prompt: 'both hands resting lightly on waist, elbows angled outward, showing full sweater front, confident fashion catalog pose, clean commercial knitwear display' },
  { id: '22', name: '半侧身站姿', prompt: 'half side standing pose, body turned 30 degrees, head facing camera, one hand on hip, showing side silhouette and sweater thickness, realistic ecommerce pose' },
  { id: '23', name: '侧身回头', prompt: 'side body angle, looking back over shoulder, natural neck curve, showing side and back garment line, soft feminine silhouette, commercial fashion pose' },
  { id: '24', name: '背面回头', prompt: 'back view pose, model looking back over shoulder, showing sweater back design, hair naturally falling, realistic body twist, ecommerce back-view clothing pose' },
  { id: '25', name: '背面站姿', prompt: 'full back standing pose, arms relaxed, shoulders natural, showing back length and shoulder seam, clean product display, realistic sweater back view' },
  { id: '26', name: '半转身抓拍', prompt: 'mid-turn pose, body rotating naturally, soft fabric movement, hair slightly moving, realistic knitwear folds, casual commercial fashion motion pose' },
  { id: '27', name: '自然行走', prompt: 'natural walking pose, one foot stepping forward, subtle arm swing, fabric moving softly, realistic body balance, commercial lifestyle knitwear pose' },
  { id: '28', name: '慢步侧走', prompt: 'side walking pose, body in profile, one hand near pocket, cardigan draping naturally, realistic leg movement, clean fashion ecommerce motion pose' },
  { id: '29', name: '单腿重心', prompt: 'weight shifted onto one leg, other knee slightly bent, subtle hip tilt, relaxed shoulders, flattering long-leg posture, SHEIN style standing pose' },
  { id: '30', name: '双腿交叉站姿', prompt: 'legs crossed naturally at ankles, elegant relaxed balance, slight body angle, arms soft, showing sweater front, premium ecommerce knitwear pose' },
  { id: '31', name: '一脚前伸', prompt: 'one foot placed forward, knee softly bent, body upright, visually lengthening legs, clean full-body apparel display, realistic fashion model stance' },
  { id: '32', name: '坐姿正面', prompt: 'relaxed sitting pose facing camera, knees slightly apart or angled, hands resting naturally, sweater folds visible, realistic body weight, cozy knitwear lifestyle pose' },
  { id: '33', name: '坐姿一手撑腿', prompt: 'seated pose, one hand resting on thigh, other hand touching cardigan front, natural fabric compression, relaxed cozy feeling, realistic SHEIN style knitwear pose' },
  { id: '34', name: '坐姿微后仰', prompt: 'relaxed seated pose leaning slightly back, shoulders soft, cardigan draped naturally, legs angled, cozy lifestyle ecommerce fashion pose' },
  { id: '35', name: '靠墙站姿', prompt: 'leaning lightly against a plain wall, one knee bent, arms relaxed, casual fashion attitude, knitwear clearly visible, minimal SHEIN style commercial pose' },
  { id: '36', name: '手拿咖啡杯', prompt: 'one hand holding coffee cup near mouth, other hand in jeans pocket, cardigan front visible, cozy lifestyle knitwear mood, natural commercial fashion pose' },
  { id: '37', name: '手拿手机自拍感', prompt: 'one hand holding phone near face, mirror selfie inspired pose, cardigan or sweater front visible, casual influencer ecommerce style, realistic relaxed posture' },
  { id: '38', name: '手拿包包', prompt: 'one hand holding small shoulder bag, other hand relaxed or on waist, cardigan draping naturally, casual urban fashion pose, SHEIN style ecommerce styling' },
  { id: '39', name: '肩背包姿势', prompt: 'small shoulder bag on one shoulder, one arm relaxed, other hand touching cardigan opening, natural lifestyle fashion pose, knitwear front clearly displayed' },
  { id: '40', name: '轻抬手臂展示袖型', prompt: 'one arm slightly raised outward, showing sleeve volume and ribbed cuff, relaxed wrist, natural shoulder line, realistic oversized knitwear display pose' },
  { id: '41', name: '双臂微张展示开衫', prompt: 'both arms slightly opened, cardigan hanging naturally, showing width, sleeve volume and front opening, realistic fabric drape, ecommerce cardigan display pose' },
  { id: '42', name: '手拉袖口', prompt: 'one hand gently pulling opposite sleeve cuff, showing ribbed cuff detail and knit elasticity, cozy sweater gesture, realistic close fashion pose' },
  { id: '43', name: '卷袖动作', prompt: 'one hand pushing sleeve upward, realistic bunching fabric around forearm, showing knit thickness and elasticity, natural lifestyle apparel pose' },
  { id: '44', name: '低头看衣服', prompt: 'model looking down at sweater, hands near hem or collar, soft neck angle, focus on garment texture, realistic ecommerce knitwear pose' },
  { id: '45', name: '低头整理衣摆', prompt: 'model looking down, both hands adjusting sweater hem, natural fabric folds, showing front length and fit, commercial clothing detail pose' },
  { id: '46', name: '自然微笑站姿', prompt: 'soft candid smile, relaxed body, one hand in pocket, natural lifestyle energy, realistic commercial sweater model pose, Instagram fashion blogger feeling' },
  { id: '47', name: '冷淡表情站姿', prompt: 'neutral expression, relaxed face, straight posture, one leg forward, clothing-focused ecommerce fashion pose, minimal SHEIN style studio look' },
  { id: '48', name: '头微侧姿势', prompt: 'head slightly tilted, shoulders relaxed, one hand touching cardigan front, soft feminine expression, sweater clearly visible, clean commercial pose' },
  { id: '49', name: '斜肩站姿', prompt: 'one shoulder slightly dropped, subtle body lean, relaxed arm position, natural slimming effect, soft knitwear silhouette, realistic ecommerce fashion pose' },
  { id: '50', name: '正面半身裁切动作', prompt: 'upper body front pose, hands lightly touching hem or button area, knit texture clearly visible, realistic torso posture, ecommerce product detail framing' },
  { id: '51', name: '胸前整理项链动作', prompt: 'one hand near necklace, elbow relaxed, cardigan neckline visible, natural feminine detail gesture, showing neckline and knit texture, commercial fashion pose' },
  { id: '52', name: '单手扶裤腰', prompt: 'one hand touching jeans waistband, other hand relaxed, emphasizing sweater length and waistline, casual SHEIN style knitwear pose, realistic body balance' },
  { id: '53', name: '双手扶裤腰', prompt: 'both hands placed near jeans waistband, thumbs slightly hooked, sweater hem visible, relaxed confident pose, commercial ecommerce styling' },
  { id: '54', name: '轻提裤腰动作', prompt: 'one hand slightly lifting or adjusting waistband, cardigan front open, casual lifestyle pose, showing crop top and knitwear length, realistic fashion posture' },
  { id: '55', name: '手插后腰', prompt: 'one hand placed behind lower back or back pocket, slight side angle, cardigan drape visible, soft feminine body curve, realistic commercial fashion pose' },
  { id: '56', name: '一手撑墙', prompt: 'one hand lightly touching wall, body angled, one leg bent, relaxed casual posture, knitwear front and side visible, minimal lifestyle ecommerce pose' },
  { id: '57', name: '靠坐沙发', prompt: 'sitting on sofa edge, cardigan draped naturally, hands resting on thighs or hem, cozy home knitwear feeling, realistic lifestyle ecommerce photography' },
  { id: '58', name: '蹲坐轻松姿势', prompt: 'casual low seated or crouched pose, knees bent naturally, oversized sweater folds visible, relaxed streetwear feeling, realistic knitwear lifestyle pose' },
  { id: '59', name: '手臂自然摆动抓拍', prompt: 'candid pose with one arm moving slightly, natural fabric motion, relaxed walking feeling, realistic ecommerce fashion movement, soft knitwear wrinkles' },
  { id: '60', name: '露肩坐姿', prompt: 'seated pose with oversized cardigan slightly slipping off one shoulder, one hand supporting on thigh, cozy feminine styling, realistic knit fabric drape' },
  { id: '61', name: '双手抱咖啡杯', prompt: 'both hands holding coffee cup near chest, cozy winter knitwear feeling, relaxed shoulders, soft feminine posture, natural lifestyle ecommerce pose, realistic sweater folds' },
  { id: '62', name: '单手喝咖啡动作', prompt: 'one hand holding takeaway coffee cup near lips, casual candid fashion moment, cardigan naturally draped, realistic lifestyle knitwear photography' },
  { id: '63', name: '扶椅背站姿', prompt: 'standing behind chair, one hand resting on chair back, relaxed body angle, long leg emphasis, cozy knitwear styling, clean commercial pose' },
  { id: '64', name: '坐姿交叉腿', prompt: 'sitting pose with legs crossed naturally, hands resting softly, sweater draping realistically, elegant feminine knitwear presentation' },
  { id: '65', name: '盘腿坐姿', prompt: 'cross-legged sitting pose, oversized sweater naturally folded, cozy relaxed atmosphere, realistic lifestyle fashion photography, soft feminine energy' },
  { id: '66', name: '沙发慵懒靠姿', prompt: 'lounging casually on sofa, cardigan draped naturally, soft body posture, realistic home lifestyle knitwear mood, ecommerce-friendly composition' },
  { id: '67', name: '趴靠桌面动作', prompt: 'leaning forward slightly on table, one elbow resting naturally, relaxed knitwear folds, soft feminine posture, lifestyle sweater presentation' },
  { id: '68', name: '轻扶下巴动作', prompt: 'one hand softly touching chin, relaxed elbow angle, subtle thoughtful expression, clean upper-body knitwear display, commercial fashion portrait pose' },
  { id: '69', name: '双手抱膝动作', prompt: 'sitting pose hugging knees softly, oversized sweater bunching naturally, cozy emotional feeling, realistic knitwear folds and texture' },
  { id: '70', name: '双手撑地坐姿', prompt: 'sitting with both hands supporting body behind, relaxed shoulders, natural oversized knit drape, casual lifestyle ecommerce pose' },
  { id: '71', name: '靠窗站姿', prompt: 'standing near large window, soft natural light, relaxed cardigan styling, subtle lifestyle atmosphere, realistic commercial fashion photography' },
  { id: '72', name: '窗边回头动作', prompt: 'looking back toward camera near window, soft natural light on knit fabric, realistic feminine movement, lifestyle knitwear pose' },
  { id: '73', name: '边走边整理衣服', prompt: 'walking naturally while adjusting cardigan or sweater hem, subtle motion realism, natural fabric movement, casual ecommerce fashion pose' },
  { id: '74', name: '边走边摸头发', prompt: 'walking pose with one hand touching hair, realistic movement, soft cardigan wrinkles, natural influencer style fashion pose' },
  { id: '75', name: '低头微笑抓拍', prompt: 'looking downward with soft candid smile, natural feminine emotion, cozy knitwear atmosphere, realistic ecommerce lifestyle photography' },
  { id: '76', name: '微风吹动头发', prompt: 'soft wind moving hair naturally, realistic cardigan folds, subtle lifestyle motion feeling, clean commercial knitwear pose' },
  { id: '77', name: '双手背后站姿', prompt: 'both hands behind back, shoulders relaxed, clean front silhouette presentation, natural feminine standing posture, minimal ecommerce styling' },
  { id: '78', name: '单手背后动作', prompt: 'one hand behind lower back, slight body twist, elegant feminine curve, sweater front clearly visible, realistic fashion catalog pose' },
  { id: '79', name: '身体前倾动作', prompt: 'slight forward lean, natural body balance, subtle playful feminine posture, realistic knitwear folds around waist and shoulders' },
  { id: '80', name: '身体轻后仰动作', prompt: 'slight backward lean, relaxed chest posture, natural cardigan drape, soft confident fashion mood, realistic lifestyle knitwear pose' },
  { id: '81', name: '双手扶大腿动作', prompt: 'both hands resting softly on thighs, seated or standing posture, natural sweater folds, clean commercial knitwear presentation' },
  { id: '82', name: '单手扶脖子动作', prompt: 'one hand softly touching neck, relaxed shoulder line, subtle feminine elegance, realistic sweater neckline display' },
  { id: '83', name: '手扶耳后头发', prompt: 'one hand tucking hair behind ear, soft candid movement, clean neckline visibility, cozy sweater styling, realistic ecommerce pose' },
  { id: '84', name: '回头轻笑动作', prompt: 'looking back with subtle smile, natural shoulder twist, soft hair flow, lifestyle fashion ecommerce photography' },
  { id: '85', name: '开衫甩动动作', prompt: 'light cardigan movement while turning or walking, realistic fabric swing, natural knit drape, cinematic ecommerce fashion motion pose' },
  { id: '86', name: '双手拉开开衫', prompt: 'both hands lightly pulling cardigan sides outward, showing inner outfit layering, realistic knit tension and structure display' },
  { id: '87', name: '一手抓袖口动作', prompt: 'one hand lightly gripping sleeve cuff, cozy winter sweater feeling, showing rib knit texture, realistic feminine gesture' },
  { id: '88', name: '半蹲姿势', prompt: 'soft half squat pose, elbows relaxed on knees or side, oversized knitwear folds naturally, casual streetwear knit fashion pose' },
  { id: '89', name: '楼梯坐姿', prompt: 'sitting casually on stairs, cardigan draped naturally, relaxed body angle, realistic lifestyle knitwear mood' },
  { id: '90', name: '楼梯行走动作', prompt: 'walking on stairs naturally, soft fabric motion, realistic body balance, lifestyle commercial knitwear photography' },
  { id: '91', name: '靠栏杆动作', prompt: 'leaning lightly on railing, relaxed urban fashion attitude, cardigan flowing naturally, realistic lifestyle ecommerce pose' },
  { id: '92', name: '街头行走动作', prompt: 'walking confidently on city street, natural knitwear folds, soft casual fashion energy, realistic influencer ecommerce photography' },
  { id: '93', name: '回头行走动作', prompt: 'walking away while looking back toward camera, subtle body twist, realistic cardigan movement, cinematic lifestyle knitwear pose' },
  { id: '94', name: '双手插大衣口袋动作', prompt: 'both hands inside coat or cardigan pockets, relaxed winter posture, cozy oversized knitwear styling, realistic fashion ecommerce pose' },
  { id: '95', name: '双臂抱自己动作', prompt: 'arms gently wrapped around body, cozy emotional winter fashion feeling, realistic sweater compression and folds' },
  { id: '96', name: '轻抬肩动作', prompt: 'slightly raised shoulder pose, soft playful fashion emotion, realistic knit tension near neckline and shoulder seam' },
  { id: '97', name: '拉高领动作', prompt: 'one hand lightly pulling up turtleneck collar, cozy winter knitwear feeling, realistic neck and fabric folds' },
  { id: '98', name: '手扶帽子动作', prompt: 'one hand touching beanie or hood naturally, relaxed winter posture, cozy sweater styling, realistic lifestyle fashion pose' },
  { id: '99', name: '拉链整理动作', prompt: 'one hand adjusting zipper naturally, realistic sleeve wrinkles, focus on cardigan or knitwear structure detail' },
  { id: '100', name: '镜前整理衣服动作', prompt: 'standing in front of mirror while adjusting sweater hem or sleeves, casual influencer vibe, realistic candid knitwear pose' },
  { id: '101', name: '低头整理袖口', prompt: 'looking down while adjusting sleeve cuff, realistic fabric bunching, soft feminine commercial pose' },
  { id: '102', name: '站姿双脚微分开', prompt: 'standing with feet slightly apart, balanced body weight, clean front garment display, relaxed ecommerce knitwear posture' },
  { id: '103', name: '手扶桌边动作', prompt: 'one hand resting on table edge, body angled slightly, realistic knitwear drape, casual premium fashion pose' },
  { id: '104', name: '坐姿托脸动作', prompt: 'seated pose with chin resting softly on hand, cozy relaxed sweater atmosphere, realistic lifestyle ecommerce portrait' },
  { id: '105', name: '双手撑腰后仰', prompt: 'both hands near waist while leaning back slightly, confident fashion stance, emphasizing garment silhouette and fit' },
  { id: '106', name: '轻抬下巴动作', prompt: 'slightly raised chin, relaxed neck posture, clean editorial-inspired ecommerce knitwear pose, premium feminine confidence' },
  { id: '107', name: '侧身扶腰动作', prompt: 'side body angle with one hand on waist, long leg emphasis, showing side silhouette and knit thickness' },
  { id: '108', name: '抬腿跨步动作', prompt: 'one leg stepping forward naturally, subtle movement realism, sweater folds responding naturally to body motion' },
  { id: '109', name: '边笑边走动作', prompt: 'walking naturally with soft smile, realistic candid lifestyle energy, commercial knitwear influencer style' },
  { id: '110', name: '双手自然甩动动作', prompt: 'arms naturally swinging while walking, realistic body motion, soft knitwear wrinkles and drape, casual commercial pose' },
  { id: '111', name: '双手提包站姿', prompt: 'both hands lightly holding handbag straps, relaxed shoulders, clean front knitwear display, soft feminine fashion posture, realistic ecommerce styling' },
  { id: '112', name: '单手提包回头动作', prompt: 'one hand holding shoulder bag while looking back over shoulder, natural cardigan movement, casual city fashion vibe' },
  { id: '113', name: '轻扶帽檐动作', prompt: 'one hand lightly touching cap or hat brim, relaxed upper body, cozy knitwear styling, casual influencer fashion pose' },
  { id: '114', name: '单手拿太阳镜动作', prompt: 'one hand holding sunglasses near chest, clean lifestyle styling, realistic feminine gesture, premium casual knitwear mood' },
  { id: '115', name: '双手捧脸动作', prompt: 'both hands softly near cheeks, oversized sleeves covering wrists slightly, cozy cute knitwear atmosphere, realistic lifestyle pose' },
  { id: '116', name: '扶肩动作', prompt: 'one hand touching opposite shoulder, soft crossed body line, realistic sweater compression, elegant feminine fashion posture' },
  { id: '117', name: '轻抱手肘动作', prompt: 'one arm lightly holding opposite elbow, relaxed body posture, cozy sweater feeling, natural commercial knitwear pose' },
  { id: '118', name: '单手扶门框动作', prompt: 'one hand touching door frame naturally, relaxed standing posture, cardigan draping softly, lifestyle fashion photography pose' },
  { id: '119', name: '靠门框站姿', prompt: 'leaning casually against doorway, one knee slightly bent, soft natural light, realistic cozy knitwear atmosphere' },
  { id: '120', name: '双手拿书动作', prompt: 'both hands holding book near chest or waist, intellectual lifestyle aesthetic, cozy oversized knitwear styling' },
  { id: '121', name: '单手翻书动作', prompt: 'one hand turning book pages naturally, relaxed seated posture, realistic knit folds and sleeve wrinkles' },
  { id: '122', name: '双手捧热饮动作', prompt: 'both hands around warm mug, cozy winter sweater feeling, relaxed shoulders, natural lifestyle ecommerce pose' },
  { id: '123', name: '看向窗外动作', prompt: 'looking softly out window, natural side lighting, calm feminine emotion, realistic cardigan drape and folds' },
  { id: '124', name: '坐姿翘腿动作', prompt: 'seated pose with one leg crossed over the other, elegant feminine posture, realistic oversized knitwear draping' },
  { id: '125', name: '沙发侧躺动作', prompt: 'lying casually on sofa side, cardigan naturally folded, cozy lifestyle atmosphere, realistic knitwear homewear styling' },
  { id: '126', name: '双手托腮动作', prompt: 'both hands supporting chin softly, relaxed elbows, cozy oversized sweater feeling, clean feminine portrait pose' },
  { id: '127', name: '抬手伸懒腰动作', prompt: 'arms slightly raised as if stretching naturally, realistic knit tension around shoulders and sleeves, cozy lifestyle fashion moment' },
  { id: '128', name: '抬手整理头发动作', prompt: 'both hands loosely gathering hair, relaxed elbows, natural upper body movement, realistic knitwear folds around shoulders' },
  { id: '129', name: '单手撑头动作', prompt: 'one hand supporting side of head, relaxed seated posture, cozy emotional sweater atmosphere' },
  { id: '130', name: '双腿蜷缩坐姿', prompt: 'knees pulled slightly toward body while seated, oversized sweater bunching naturally, soft cozy winter mood' },
  { id: '131', name: '单手扶膝动作', prompt: 'one hand resting naturally on bent knee, relaxed body posture, realistic lifestyle knitwear photography' },
  { id: '132', name: '半蹲扶膝动作', prompt: 'half squat pose with one hand on knee, relaxed body angle, casual streetwear knitwear aesthetic' },
  { id: '133', name: '双手环抱咖啡动作', prompt: 'holding warm coffee cup close to chest with both hands, cozy winter cardigan mood, realistic knit compression' },
  { id: '134', name: '手插卫衣口袋动作', prompt: 'both hands inside hoodie or sweater pouch pocket, relaxed oversized knitwear styling, casual ecommerce fashion pose' },
  { id: '135', name: '衣服遮嘴动作', prompt: 'sweater sleeves partially covering mouth, cozy shy feminine energy, oversized knitwear aesthetic, realistic winter mood' },
  { id: '136', name: '单手轻扶太阳穴', prompt: 'one hand softly touching temple area, calm elegant feminine posture, realistic upper body knitwear presentation' },
  { id: '137', name: '双手后撑坐姿', prompt: 'sitting pose with both hands supporting body behind, relaxed chest posture, natural oversized knit folds' },
  { id: '138', name: '坐姿侧身回头', prompt: 'seated side pose looking back over shoulder, natural spine twist, realistic cardigan drape' },
  { id: '139', name: '坐姿托腿动作', prompt: 'sitting pose hugging one knee softly, cozy emotional sweater styling, realistic knit texture and wrinkles' },
  { id: '140', name: '抬腿踩椅动作', prompt: 'one foot placed casually on chair edge, relaxed upper body posture, natural oversized knit folds' },
  { id: '141', name: '倚靠桌边动作', prompt: 'leaning casually on table edge with hip support, relaxed shoulders, premium lifestyle knitwear pose' },
  { id: '142', name: '身体轻靠栏杆动作', prompt: 'body lightly leaning against railing, one hand relaxed near waist, realistic urban lifestyle sweater photography' },
  { id: '143', name: '双手放背后走路动作', prompt: 'walking with both hands behind back, relaxed feminine confidence, soft cardigan movement, realistic fashion motion' },
  { id: '144', name: '回头微笑行走动作', prompt: 'walking away while smiling softly back at camera, realistic knit movement, lifestyle influencer energy' },
  { id: '145', name: '侧身插兜动作', prompt: 'side body pose with one hand in pocket, emphasizing waistline and side silhouette, realistic sweater drape' },
  { id: '146', name: '双手撑腰站立动作', prompt: 'both hands on hips, shoulders relaxed, confident feminine stance, clean front knitwear presentation' },
  { id: '147', name: '双臂下垂冷淡站姿', prompt: 'arms naturally hanging, neutral expression, minimalist commercial fashion pose, strong clothing focus' },
  { id: '148', name: '身体轻微S曲线动作', prompt: 'subtle S-curve body posture, relaxed hips and shoulders, feminine silhouette emphasis, realistic fashion balance' },
  { id: '149', name: '单脚点地动作', prompt: 'one foot lightly touching ground, relaxed weight distribution, elegant feminine standing balance' },
  { id: '150', name: '双脚前后站姿', prompt: 'feet positioned naturally front and back, elongated leg effect, casual ecommerce knitwear stance' },
  { id: '151', name: '双手抱包动作', prompt: 'both hands holding handbag in front naturally, cozy feminine citywear styling' },
  { id: '152', name: '一手拎包一手插兜', prompt: 'one hand carrying handbag, other hand casually inside pocket, realistic urban knitwear fashion pose' },
  { id: '153', name: '双手拉开外套动作', prompt: 'both hands slightly pulling cardigan or coat open, showing inner outfit layering, realistic knit structure' },
  { id: '154', name: '坐姿低头看手机动作', prompt: 'sitting while looking at phone naturally, realistic upper body posture, cozy oversized knitwear lifestyle scene' },
  { id: '155', name: '边走边看手机动作', prompt: 'walking naturally while looking at phone, subtle candid lifestyle energy, realistic fabric movement' },
  { id: '156', name: '单手扶椅坐姿', prompt: 'one hand resting on chair arm, relaxed seated posture, realistic sweater draping and folds' },
  { id: '157', name: '双手自然搭腿动作', prompt: 'both hands resting softly on thighs while seated, elegant relaxed knitwear presentation' },
  { id: '158', name: '坐姿托头发动作', prompt: 'seated pose with one hand running through hair, soft feminine mood, realistic upper body knit folds' },
  { id: '159', name: '微侧脸特写动作', prompt: 'slight side profile close-up, natural soft expression, knit collar detail visible, premium ecommerce portrait framing' },
  { id: '160', name: '半身抱臂特写动作', prompt: 'upper body crossed-arm pose, cozy knit texture emphasized, relaxed commercial sweater portrait' }
];
