export interface LongDressPose {
  id: string;
  name: string;
  prompt: string;
}

const LONG_DRESS_FRAME =
  'commercial hero-image framing for a long dress or maxi dress, full garment silhouette visible from neckline/shoulders to hem and footwear when relevant, elegant feminine proportions, dress drape, hem, fabric flow, waistline, sleeve/strap details, and full length clearly readable, no cropped-off dress hem, premium ecommerce fashion editorial';

const LONG_DRESS_POSE_PROMPTS = [
  'Leaning against a parisian stone wall, arms relaxed naturally, editorial luxury fashion mood',
  'One shoulder touching the wall, elongated body line, relaxed paris fashion week aesthetic',
  'Legs crossed naturally while leaning against architectural facade, minimal emotion',
  'One hand resting inside pocket, quiet confidence, luxury european street style',
  'Both hands inside pockets, oversized silhouette, effortless editorial posture',
  'Holding handbag under arm while standing against wall, modern paris lookbook',
  'One hand resting on waist, emphasizing body proportion and dress silhouette',
  'Arms hanging naturally beside body, clean luxury fashion campaign pose',
  'One hand lightly touching textured stone wall, architectural editorial styling',
  'Back leaning against wall, looking away from camera, european fashion attitude',
  'Walking directly toward camera with long confident stride, fashion week street style',
  'Side-profile walking pose, dress flowing naturally with movement',
  'Walking away while glancing back over shoulder softly',
  'Long runway-inspired stride, strong silhouette, luxury editorial mood',
  'Walking with wind lifting dress hem naturally',
  'Crossing parisian street naturally, candid luxury fashion photography',
  'Walking along european cobblestone street, elegant city movement',
  'Turning around architectural street corner naturally',
  'Holding handbag while walking confidently through city scene',
  'Hands in pockets while walking, effortless luxury attitude',
  'Front-facing standing pose, neutral expression, clean editorial composition',
  'Three-quarter standing angle, highlighting garment drape',
  'Slightly rotated body position, natural fashion catalog posture',
  'Looking toward distant city horizon, calm emotional expression',
  'Looking downward softly, relaxed luxury styling',
  'Slight head raise, elegant neck line exposure',
  'Eyes closed under warm sunlight, european fashion campaign mood',
  'Weight shifted onto one leg, elongated feminine silhouette',
  'Legs crossed naturally, luxury editorial balance',
  'One foot slightly forward, runway-inspired stance',
  'Mid-turn movement pose, natural dress motion',
  'Half-turn body movement, cinematic fashion storytelling',
  'Looking back over shoulder with subtle attitude',
  'Looking downward while turning naturally',
  'Dress moving softly during body rotation',
  'Single-leg pivot movement, editorial elegance',
  'Wind-blown hair and dress during turning motion',
  'Holding handbag while rotating body naturally',
  'Turning with lowered gaze, luxury magazine atmosphere',
  'Back facing camera while head turns sideways',
  'Arms crossed softly, luxury confidence posture',
  'One hand touching opposite arm naturally',
  'Fingers resting near collarbone, elegant gesture',
  'One hand lightly touching neck',
  'Natural hair adjustment movement',
  'Wind-blown hair editorial moment',
  'Holding clutch under arm naturally',
  'Holding handbag with both hands in front of body',
  'Handbag hanging loosely beside body',
  'Symmetrical standing pose with arms relaxed',
  'Standing beside parisian window facade',
  'Standing within european doorway frame',
  'Leaning beside historic stone architecture',
  'Waiting naturally on quiet city street',
  'Slow walking through paris fashion district',
  'Walking through arched european architecture',
  'Standing beside classical column structure',
  'One hand touching architectural column',
  'Holding bag while observing city surroundings',
  'Looking back while walking down narrow european street',
  'Standing beside textured limestone wall',
  'Standing under directional sunlight and shadow geometry',
  'Leaning beside old paris apartment facade',
  'Standing in front of luxury boutique storefront',
  'Walking beside historic european building',
  'Standing beneath balcony shadows',
  'Crossing luxury hotel entrance',
  'Standing beside vintage french doorway',
  'Walking along stone facade with flowing dress',
  'Architectural symmetry centered standing pose',
  'Standing inside luxury courtyard',
  'Looking toward luxury hotel facade',
  'Holding clutch beside french window',
  'Slow walk through luxury residence entrance',
  'Standing beneath archway shadows',
  'Minimal pose against monochrome wall',
  'Soft side profile against textured architecture',
  'Walking beneath european building shadows',
  'Looking upward toward architectural details',
  'Standing near classic parisian corner',
  'Editorial pose beneath strong geometric shadows',
  'Large negative space composition',
  'Standing centered within architectural frame',
  'Minimal expression fashion magazine posture',
  'Long vertical silhouette composition',
  'Dramatic sunlight cutting across body',
  'Looking away from camera completely',
  'Architectural perspective leading lines composition',
  'Static standing pose with cinematic mood',
  'Soft movement through sunlight corridor',
  'Shadow and light contrast composition',
  'Hands hidden behind body',
  'Oversized silhouette editorial stance',
  'Neutral runway waiting pose',
  'Standing against concrete architectural texture',
  'One foot stepping forward subtly',
  'Dress hem catching natural wind',
  'Strong shoulder-forward stance',
  'Looking down city street naturally',
  'Editorial luxury campaign posture',
  'Fast walking through fashion week crowd',
  'Purposeful stride carrying oversized handbag',
  'Hands in pockets during city crossing',
  'Looking down while crossing street',
  'Fashion week arrival moment',
  'Walking beside luxury hotel entrance',
  'Wind-blown long dress movement',
  'Carrying clutch under arm while walking',
  'Looking toward photographers naturally',
  'Crossing zebra crossing confidently',
  'Street-style candid walking shot',
  'Walking with sunglasses and neutral expression',
  'Long coat or dress movement during stride',
  'Looking sideways while walking',
  'Natural candid movement through city',
  'Entering fashion venue',
  'Exiting architectural building entrance',
  'Side-profile street-style stride',
  'Street corner pause moment',
  'Architectural background runway feeling',
  'Walking toward sunlight',
  'Walking away from camera naturally',
  'Standing briefly before crossing road',
  'Looking at passing traffic casually',
  'Hand touching sunglasses while walking',
  'Holding garment lightly while moving',
  'Bag swinging naturally with movement',
  'Strong forward momentum pose',
  'Looking over shoulder while walking',
  'Wind catching dress during city walk',
  'Long elegant step with flowing silhouette',
  'Minimalist fashion week street pose',
  'City crosswalk editorial composition',
  'Walking beside luxury storefront',
  'Architectural perspective street shot',
  'Confident model-off-duty posture',
  'Fast-paced urban fashion movement',
  'Looking ahead with determination',
  'Street-style documentary aesthetic',
  'City sidewalk luxury campaign pose',
  'Standing beneath dramatic sunlight',
  'Standing beneath building shadow edge',
  'Leaning against concrete structure',
  'Looking through oversized sunglasses',
  'One hand resting on handbag strap',
  'One hand touching waist naturally',
  'Looking across city avenue',
  'Relaxed luxury fashion attitude',
  'Minimal emotion editorial gaze',
  'Architectural luxury lookbook posture',
  'Fashion week arrival stride',
  'Street-style runway walk',
  'Luxury city walking campaign',
  'European editorial architecture pose',
  'Modern minimalist luxury stance',
  'Soft cinematic movement shot',
  'Looking away beneath warm sunlight',
  'Architectural wall leaning pose',
  'Confident oversized silhouette stance',
  'Relaxed luxury handbag styling',
  'Wind-blown fashion week moment',
  'Slow walk beneath old european architecture',
  'Neutral expression city editorial',
  'Standing within sunlight geometry',
  'Looking back naturally while moving',
  'Luxury magazine cover posture',
  'Elegant static composition',
  'Runway-inspired standing silhouette',
  'Soft body rotation with flowing dress',
  'Minimal hand gesture styling',
  'Architectural corridor walk',
  'Luxury residence entrance pose',
  'Street fashion documentary shot',
  'Sophisticated city woman attitude',
  'Relaxed european elegance',
  'Modern parisian luxury aesthetic',
  'Soft movement fashion storytelling',
  'Looking beyond camera naturally',
  'Editorial luxury confidence',
  'Clean silhouette against architecture',
  'Long dress flowing with stride',
  'Contemporary european fashion mood',
  'Quiet luxury standing posture',
  'Fashion editor street style look',
  'Architectural framing composition',
  'Sophisticated handbag styling pose',
  'Premium luxury campaign stance',
  'Warm sunlight editorial portrait',
  'Modern european lookbook movement',
  'City luxury fashion storytelling',
  'Minimalist luxury fashion week posture',
  'Elegant long dress silhouette',
  'Architectural city confidence',
  'Editorial calm emotion',
  'Paris fashion week candid',
  'Vogue-inspired standing pose',
  "Harper's Bazaar editorial mood",
  'Luxury magazine campaign posture',
  'The Row inspired quiet luxury stance',
  'Final paris fashion week hero pose, standing confidently within grand european architecture, flowing maxi dress, natural sunlight, luxury editorial fashion campaign'
];

export const LONG_DRESS_POSES: LongDressPose[] = LONG_DRESS_POSE_PROMPTS.map((prompt, index) => {
  const id = String(index + 1).padStart(3, '0');
  return {
    id,
    name: `Long Dress ${id}`,
    prompt: `${prompt}, ${LONG_DRESS_FRAME}`,
  };
});
