export interface MensTeePose {
  id: string;
  name: string;
  prompt: string;
}

export const MENS_TEE_POSES: MensTeePose[] = [
  { id: '001', name: '双手自然下垂', prompt: 'arms naturally hanging down, relaxed oversized tee silhouette, effortless summer styling' },
  { id: '002', name: '单手插短裤口袋', prompt: 'one hand in shorts pocket, oversized tee draping naturally' },
  { id: '003', name: '双手插口袋', prompt: 'both hands in pockets, relaxed california boy aesthetic' },
  { id: '004', name: '单腿重心', prompt: 'weight shifted onto one leg, relaxed oversized silhouette' },
  { id: '005', name: '双腿交叉站姿', prompt: 'legs crossed naturally, casual summer menswear mood' },
  { id: '006', name: '单手抓衣摆', prompt: 'holding oversized tee hem casually, showing fabric drape' },
  { id: '007', name: '双手抓衣摆', prompt: 'holding both sides of shirt hem, showing oversized fit' },
  { id: '008', name: '单手扶后颈', prompt: 'one hand touching back of neck, summer relaxed atmosphere' },
  { id: '009', name: '单手摸头发', prompt: 'one hand running through hair naturally, california lifestyle aesthetic' },
  { id: '010', name: '双手背后', prompt: 'hands behind back, clean oversized tee display' },
  { id: '011', name: '单手背后', prompt: 'one hand behind body, relaxed masculine silhouette' },
  { id: '012', name: '低头动作', prompt: 'looking downward naturally, casual oversized styling' },
  { id: '013', name: '回头动作', prompt: 'looking back over shoulder, street vacation mood' },
  { id: '014', name: '回头微笑', prompt: 'soft smile, looking back naturally' },
  { id: '015', name: '看向远方', prompt: 'looking toward horizon, summer lifestyle campaign' },
  { id: '016', name: '闭眼晒太阳', prompt: 'eyes closed naturally, warm sunlight atmosphere' },
  { id: '017', name: '身体微后仰', prompt: 'slight backward lean, relaxed confidence' },
  { id: '018', name: '身体微前倾', prompt: 'slight forward lean, casual conversation feeling' },
  { id: '019', name: '单手扶腰', prompt: 'one hand on waist, oversized tee campaign' },
  { id: '020', name: '双手扶腰', prompt: 'hands near waist, casual summer styling' },
  { id: '021', name: '单手拿墨镜', prompt: 'holding sunglasses casually, beach club aesthetic' },
  { id: '022', name: '整理墨镜动作', prompt: 'adjusting sunglasses naturally' },
  { id: '023', name: '单手拿咖啡', prompt: 'holding iced coffee casually, california lifestyle mood' },
  { id: '024', name: '单手拿手机', prompt: 'holding smartphone naturally, street vacation vibe' },
  { id: '025', name: '边走边看手机', prompt: 'walking casually, looking at phone, summer lifestyle aesthetic' },
  { id: '026', name: '行走抓拍', prompt: 'walking naturally, oversized shirt moving softly' },
  { id: '027', name: '边走边笑', prompt: 'walking with subtle smile, california beach atmosphere' },
  { id: '028', name: '行走回头', prompt: 'walking away, looking back casually' },
  { id: '029', name: '双手插兜行走', prompt: 'walking with both hands in pockets' },
  { id: '030', name: '单手插兜行走', prompt: 'walking casually, one hand in pocket' },
  { id: '031', name: '单手拿滑板', prompt: 'holding skateboard beside body, summer skater aesthetic' },
  { id: '032', name: '扛滑板动作', prompt: 'skateboard resting on shoulder, california boy styling' },
  { id: '033', name: '单手拿冲浪板', prompt: 'holding surfboard casually, beach lifestyle campaign' },
  { id: '034', name: '靠冲浪板站姿', prompt: 'leaning naturally against surfboard' },
  { id: '035', name: '沙滩漫步动作', prompt: 'walking barefoot on sand, oversized tee movement' },
  { id: '036', name: '海边看海动作', prompt: 'standing near shoreline, looking toward ocean' },
  { id: '037', name: '海边回头动作', prompt: 'looking back naturally, beach club mood' },
  { id: '038', name: '单手扶栏杆', prompt: 'one hand resting on railing, coastal aesthetic' },
  { id: '039', name: '靠栏杆动作', prompt: 'leaning casually on railing' },
  { id: '040', name: '单手扶墙', prompt: 'touching wall naturally, street summer atmosphere' },
  { id: '041', name: '靠墙站姿', prompt: 'leaning against wall, relaxed oversized tee campaign' },
  { id: '042', name: '单脚靠墙动作', prompt: 'one foot against wall, casual skater mood' },
  { id: '043', name: '坐台阶动作', prompt: 'sitting casually on stairs' },
  { id: '044', name: '坐台阶扶膝', prompt: 'sitting on stairs, hands resting on knees' },
  { id: '045', name: '坐姿低头动作', prompt: 'sitting naturally, looking downward' },
  { id: '046', name: '坐姿看远方', prompt: 'sitting casually, looking toward horizon' },
  { id: '047', name: '单手撑地动作', prompt: 'one hand supporting body, relaxed beach aesthetic' },
  { id: '048', name: '单手扶帽檐', prompt: 'touching cap brim naturally' },
  { id: '049', name: '调整帽子动作', prompt: 'adjusting baseball cap casually' },
  { id: '050', name: '双手插短裤口袋看海', prompt: 'both hands in pockets, standing near ocean' },
  { id: '051', name: '泳池边站姿', prompt: 'standing beside swimming pool, oversized tee draping naturally, resort lifestyle atmosphere' },
  { id: '052', name: '泳池边插兜', prompt: 'hands inside shorts pockets, relaxed beach club mood' },
  { id: '053', name: '泳池边看远方', prompt: 'looking toward distance, warm sunlight, vacation aesthetic' },
  { id: '054', name: '泳池边回头', prompt: 'looking back naturally, summer travel campaign' },
  { id: '055', name: '泳池边拿饮料', prompt: 'holding iced drink casually, pool club atmosphere' },
  { id: '056', name: '单手扶泳池栏杆', prompt: 'one hand resting on pool railing, california resort vibe' },
  { id: '057', name: '双手扶栏杆', prompt: 'both hands resting naturally, relaxed masculine silhouette' },
  { id: '058', name: '棕榈树下站姿', prompt: 'standing under palm trees, oversized tee campaign, summer travel mood' },
  { id: '059', name: '棕榈树下插兜', prompt: 'hands inside pockets, beach vacation atmosphere' },
  { id: '060', name: '棕榈树下回头', prompt: 'looking back softly, warm sunlight' },
  { id: '061', name: '棕榈树下行走', prompt: 'walking casually, tee moving naturally' },
  { id: '062', name: '单手拿椰子', prompt: 'holding coconut drink casually, tropical vacation aesthetic' },
  { id: '063', name: '单手拿冰饮', prompt: 'holding iced beverage naturally, summer lifestyle campaign' },
  { id: '064', name: '海边咖啡馆站姿', prompt: 'standing outside beach cafe, oversized tee styling' },
  { id: '065', name: '海边咖啡馆坐姿', prompt: 'sitting casually outdoors, summer vacation atmosphere' },
  { id: '066', name: '单手扶桌面', prompt: 'one hand resting on cafe table, relaxed california mood' },
  { id: '067', name: '单手拿菜单', prompt: 'holding menu casually, beach club aesthetic' },
  { id: '068', name: '单手拿咖啡', prompt: 'holding coffee naturally, summer travel vibe' },
  { id: '069', name: '边喝咖啡边看海', prompt: 'drinking coffee while looking toward ocean' },
  { id: '070', name: '海边木栈道行走', prompt: 'walking along boardwalk, oversized tee movement' },
  { id: '071', name: '木栈道回头', prompt: 'looking back naturally, beach lifestyle campaign' },
  { id: '072', name: '木栈道插兜', prompt: 'hands in pockets, walking casually' },
  { id: '073', name: '靠木栏杆动作', prompt: 'leaning naturally against wooden railing' },
  { id: '074', name: '双手撑木栏杆', prompt: 'both hands resting on railing, oceanfront atmosphere' },
  { id: '075', name: '看海发呆动作', prompt: 'standing still, looking toward ocean horizon, vacation lifestyle aesthetic' },
  { id: '076', name: '城市街头漫步', prompt: 'walking naturally through city street, oversized tee moving softly' },
  { id: '077', name: '单手插兜走路', prompt: 'one hand inside pocket, casual summer movement' },
  { id: '078', name: '双手插兜走路', prompt: 'both hands in pockets, street vacation aesthetic' },
  { id: '079', name: '边走边看远方', prompt: 'walking naturally, looking toward distance' },
  { id: '080', name: '边走边笑', prompt: 'soft smile, summer lifestyle campaign' },
  { id: '081', name: '单手拿耳机', prompt: 'holding headphones casually, travel boy aesthetic' },
  { id: '082', name: '戴耳机动作', prompt: 'wearing headphones naturally, urban vacation styling' },
  { id: '083', name: '单手拿相机', prompt: 'holding camera casually, travel photography vibe' },
  { id: '084', name: '相机挂脖动作', prompt: 'camera hanging around neck, vacation explorer mood' },
  { id: '085', name: '单手拿背包肩带', prompt: 'holding backpack strap casually' },
  { id: '086', name: '双手扶背包肩带', prompt: 'both hands holding backpack straps, travel lifestyle campaign' },
  { id: '087', name: '靠墙站姿', prompt: 'leaning casually against wall, street resort aesthetic' },
  { id: '088', name: '单脚靠墙', prompt: 'one foot against wall, relaxed masculine posture' },
  { id: '089', name: '单手扶墙动作', prompt: 'touching wall naturally, urban summer mood' },
  { id: '090', name: '看橱窗动作', prompt: 'looking into storefront naturally, travel city aesthetic' },
  { id: '091', name: '等红绿灯动作', prompt: 'standing casually on street corner, oversized tee campaign' },
  { id: '092', name: '坐长椅动作', prompt: 'sitting casually on bench' },
  { id: '093', name: '长椅低头动作', prompt: 'sitting naturally, looking downward' },
  { id: '094', name: '长椅看远方', prompt: 'looking toward distance, travel mood' },
  { id: '095', name: '单手拿手机发消息', prompt: 'using smartphone naturally, summer lifestyle vibe' },
  { id: '096', name: '双手拿手机', prompt: 'holding phone casually, urban travel campaign' },
  { id: '097', name: '查看导航动作', prompt: 'looking at smartphone map, travel boy aesthetic' },
  { id: '098', name: '回头看镜头动作', prompt: 'looking back casually, street vacation mood' },
  { id: '099', name: '闭眼晒太阳动作', prompt: 'eyes closed naturally, warm urban sunlight' },
  { id: '100', name: '双手背后行走', prompt: 'walking naturally, hands behind back, effortless oversized tee styling' },
];
