export interface MensShortsPose {
  id: string;
  name: string;
  prompt: string;
}

const MENS_SHORTS_FRAME =
  'commercial mens shorts product display, this is regular casual shorts not swim shorts or swimwear, default crop is lower-torso/waist-to-shoes or waist-to-knees depending on the pose, do not show full body or full face unless the user explicitly requests full-body, keep the shorts as the central product focus, show waistband, pockets, side seams, hem, leg opening, inseam length, fit and fabric drape clearly, realistic menswear proportions, clean SHEIN menswear campaign styling';

const withFrame = (prompt: string) => `${prompt}, ${MENS_SHORTS_FRAME}`;

export const MENS_SHORTS_POSES: MensShortsPose[] = [
  { id: '001', name: '正面站立', prompt: withFrame('front standing pose, feet shoulder-width apart, focus on shorts silhouette') },
  { id: '002', name: '微侧身站立', prompt: withFrame('three-quarter body angle, showing side profile') },
  { id: '003', name: '左侧站立', prompt: withFrame('left side profile display') },
  { id: '004', name: '右侧站立', prompt: withFrame('right side profile display') },
  { id: '005', name: '背面站立', prompt: withFrame('back view shorts display') },
  { id: '006', name: '单腿重心', prompt: withFrame('weight shifted onto one leg') },
  { id: '007', name: '双腿微分开', prompt: withFrame('relaxed stance, showing leg opening') },
  { id: '008', name: '单脚前探', prompt: withFrame('one foot slightly forward') },
  { id: '009', name: '双脚交叉', prompt: withFrame('crossed leg stance') },
  { id: '010', name: '单脚后撤', prompt: withFrame('one foot slightly behind') },
  { id: '011', name: '单手插口袋', prompt: withFrame('one hand inside pocket') },
  { id: '012', name: '双手插口袋', prompt: withFrame('both hands in pockets') },
  { id: '013', name: '拇指挂口袋', prompt: withFrame('thumb hooked into pocket') },
  { id: '014', name: '单手扶腰', prompt: withFrame('one hand resting on waist') },
  { id: '015', name: '双手扶腰', prompt: withFrame('hands on waist') },
  { id: '016', name: '单手扶裤腰', prompt: withFrame('touching waistband naturally') },
  { id: '017', name: '双手扶裤腰', prompt: withFrame('holding waistband casually') },
  { id: '018', name: '调整抽绳', prompt: withFrame('adjusting drawstring') },
  { id: '019', name: '系抽绳动作', prompt: withFrame('tying drawstring') },
  { id: '020', name: '展示腰头动作', prompt: withFrame('showing waistband construction') },
  { id: '021', name: '单手展示口袋', prompt: withFrame('hand partially inside pocket') },
  { id: '022', name: '双手展示口袋', prompt: withFrame('opening pockets naturally') },
  { id: '023', name: '拉出口袋布', prompt: withFrame('showing pocket depth') },
  { id: '024', name: '单手抓裤边', prompt: withFrame('holding hem lightly') },
  { id: '025', name: '双手抓裤边', prompt: withFrame('holding both sides of shorts hem') },
  { id: '026', name: '整理裤腿', prompt: withFrame('adjusting leg opening') },
  { id: '027', name: '单手扶大腿', prompt: withFrame('hand resting on thigh') },
  { id: '028', name: '双手自然下垂', prompt: withFrame('arms hanging naturally') },
  { id: '029', name: '双手背后', prompt: withFrame('hands behind body') },
  { id: '030', name: '单手背后', prompt: withFrame('one hand behind back') },
  { id: '031', name: '低头看裤子', prompt: withFrame('looking downward at shorts') },
  { id: '032', name: '看向远方', prompt: withFrame('looking away naturally') },
  { id: '033', name: '回头动作', prompt: withFrame('looking over shoulder') },
  { id: '034', name: '回头微笑', prompt: withFrame('soft smile while turning') },
  { id: '035', name: '身体微前倾', prompt: withFrame('slight forward lean') },
  { id: '036', name: '身体微后仰', prompt: withFrame('slight backward lean') },
  { id: '037', name: '靠墙站姿', prompt: withFrame('leaning against wall') },
  { id: '038', name: '单肩靠墙', prompt: withFrame('one shoulder touching wall') },
  { id: '039', name: '单脚靠墙', prompt: withFrame('one foot against wall') },
  { id: '040', name: '双手插袋靠墙', prompt: withFrame('hands in pockets, leaning casually') },
  { id: '041', name: '单手扶墙', prompt: withFrame('touching wall lightly') },
  { id: '042', name: '靠栏杆站姿', prompt: withFrame('leaning on railing') },
  { id: '043', name: '单手扶栏杆', prompt: withFrame('one hand resting on railing') },
  { id: '044', name: '双手扶栏杆', prompt: withFrame('both hands on railing') },
  { id: '045', name: '单手拿手机', prompt: withFrame('holding smartphone casually') },
  { id: '046', name: '查看手机', prompt: withFrame('looking at phone') },
  { id: '047', name: '单手拿咖啡', prompt: withFrame('holding coffee cup') },
  { id: '048', name: '单手拿饮料', prompt: withFrame('holding cold drink') },
  { id: '049', name: '单手拿钥匙', prompt: withFrame('holding keys casually') },
  { id: '050', name: '单手拿耳机', prompt: withFrame('holding headphones') },
  { id: '051', name: '慢步行走', prompt: withFrame('slow walking motion') },
  { id: '052', name: '行走抓拍', prompt: withFrame('candid walking shot') },
  { id: '053', name: '单手插袋行走', prompt: withFrame('walking with one hand in pocket') },
  { id: '054', name: '双手插袋行走', prompt: withFrame('walking with both hands in pockets') },
  { id: '055', name: '行走回头', prompt: withFrame('looking back while walking') },
  { id: '056', name: '行走低头', prompt: withFrame('looking down while walking') },
  { id: '057', name: '行走看远方', prompt: withFrame('looking ahead naturally') },
  { id: '058', name: '行走整理抽绳', prompt: withFrame('adjusting drawstring while moving') },
  { id: '059', name: '行走扶腰', prompt: withFrame('one hand on waist while walking') },
  { id: '060', name: '行走拿手机', prompt: withFrame('walking while holding phone') },
  { id: '061', name: '坐姿扶膝', prompt: withFrame('hands resting on knees') },
  { id: '062', name: '坐姿交叉腿', prompt: withFrame('legs crossed while seated') },
  { id: '063', name: '坐姿插袋', prompt: withFrame('hands inside pockets while seated') },
  { id: '064', name: '坐姿低头', prompt: withFrame('looking downward seated') },
  { id: '065', name: '台阶坐姿', prompt: withFrame('sitting on stairs') },
  { id: '066', name: '长椅坐姿', prompt: withFrame('sitting on bench') },
  { id: '067', name: '靠椅背坐姿', prompt: withFrame('leaning against chair') },
  { id: '068', name: '单腿伸展坐姿', prompt: withFrame('one leg extended') },
  { id: '069', name: '单手撑身体', prompt: withFrame('one arm supporting body') },
  { id: '070', name: '双手扶膝坐姿', prompt: withFrame('hands resting on knees') },
  { id: '071', name: '站在门框旁', prompt: withFrame('standing beside doorway') },
  { id: '072', name: '站在建筑立柱旁', prompt: withFrame('standing beside column') },
  { id: '073', name: '街头站姿', prompt: withFrame('urban streetwear stance') },
  { id: '074', name: '商场外站姿', prompt: withFrame('casual city styling') },
  { id: '075', name: '街角等待动作', prompt: withFrame('waiting naturally') },
  { id: '076', name: '看橱窗动作', prompt: withFrame('looking at storefront') },
  { id: '077', name: '等红绿灯动作', prompt: withFrame('standing at crossing') },
  { id: '078', name: '路边站姿', prompt: withFrame('standing beside road') },
  { id: '079', name: '公园站姿', prompt: withFrame('standing in park setting') },
  { id: '080', name: '木栈道站姿', prompt: withFrame('standing on boardwalk') },
  { id: '081', name: '风吹裤腿动作', prompt: withFrame('fabric moving naturally') },
  { id: '082', name: '风吹衣摆动作', prompt: withFrame('casual movement') },
  { id: '083', name: '单手扶帽檐', prompt: withFrame('touching cap brim') },
  { id: '084', name: '整理帽子动作', prompt: withFrame('adjusting baseball cap') },
  { id: '085', name: '单手摸头发', prompt: withFrame('running hand through hair') },
  { id: '086', name: '双手抱胸', prompt: withFrame('arms crossed') },
  { id: '087', name: '单手扶脖子', prompt: withFrame('touching neck casually') },
  { id: '088', name: '单手扶肩', prompt: withFrame('touching opposite shoulder') },
  { id: '089', name: '单手插后袋', prompt: withFrame('hand in back pocket') },
  { id: '090', name: '双手插后袋', prompt: withFrame('both hands in back pockets') },
  { id: '091', name: '展示侧口袋', prompt: withFrame('showing cargo pocket') },
  { id: '092', name: '展示工装口袋', prompt: withFrame('highlighting utility pocket') },
  { id: '093', name: '展示拉链口袋', prompt: withFrame('opening zipper pocket') },
  { id: '094', name: '展示裤长', prompt: withFrame('standing straight, focus on inseam length') },
  { id: '095', name: '展示宽松版型', prompt: withFrame('relaxed oversized fit') },
  { id: '096', name: '展示直筒版型', prompt: withFrame('straight fit display') },
  { id: '097', name: '展示运动版型', prompt: withFrame('athletic fit stance') },
  { id: '098', name: '展示休闲版型', prompt: withFrame('casual everyday fit') },
  { id: '099', name: '展示街头版型', prompt: withFrame('streetwear shorts styling') },
  { id: '100', name: 'Hero shorts pose', prompt: withFrame('Hero shorts pose, relaxed confidence, focus on shorts silhouette, clean shein menswear campaign') },
];
