export interface MensShirtPose {
  id: string;
  name: string;
  prompt: string;
}

export const MENS_SHIRT_POSES: MensShirtPose[] = [
  { id: '001', name: '微侧身站姿', prompt: 'three-quarter body angle, relaxed shoulders, one foot slightly forward, resort shirt naturally draped, vacation menswear campaign' },
  { id: '002', name: '单手插短裤口袋', prompt: 'one hand inside shorts pocket, relaxed summer shirt styling, effortless resort mood' },
  { id: '003', name: '双手插口袋', prompt: 'both hands inside pockets, relaxed masculine posture, coastal vacation atmosphere' },
  { id: '004', name: '低头整理衣摆', prompt: 'looking downward while adjusting shirt hem naturally, showing fabric drape' },
  { id: '005', name: '单手抓衣摆', prompt: 'holding shirt hem lightly, summer breeze feeling, relaxed resort styling' },
  { id: '006', name: '双手抓门襟', prompt: 'holding both shirt plackets naturally, shirt slightly open, resort vacation aesthetic' },
  { id: '007', name: '整理领口', prompt: 'touching shirt collar naturally, relaxed masculine energy, linen shirt campaign' },
  { id: '008', name: '解开领口动作', prompt: 'one hand opening collar slightly, casual vacation feeling' },
  { id: '009', name: '单手扶后颈', prompt: 'one hand touching back of neck, summer heat atmosphere, relaxed resort mood' },
  { id: '010', name: '双手叉腰', prompt: 'hands on waist, confident vacation styling, coastal menswear campaign' },
  { id: '011', name: '单手叉腰', prompt: 'one hand on waist, relaxed masculine silhouette, resort fashion pose' },
  { id: '012', name: '行走抓拍', prompt: 'walking naturally, shirt moving softly, summer vacation aesthetic' },
  { id: '013', name: '边走边看远方', prompt: 'walking while looking toward horizon, relaxed coastal lifestyle mood' },
  { id: '014', name: '边走边整理袖口', prompt: 'walking naturally while adjusting cuff, premium resort menswear feeling' },
  { id: '015', name: '回头动作', prompt: 'body facing away, looking back softly over shoulder, summer sunlight' },
  { id: '016', name: '回头微笑', prompt: 'looking back with subtle smile, resort vacation atmosphere' },
  { id: '017', name: '看海动作', prompt: 'standing naturally looking toward ocean horizon, relaxed masculine energy' },
  { id: '018', name: '看地面动作', prompt: 'looking downward casually, natural resort lifestyle photography' },
  { id: '019', name: '单手拿墨镜', prompt: 'holding sunglasses casually, summer vacation campaign' },
  { id: '020', name: '整理墨镜动作', prompt: 'touching sunglasses naturally, relaxed vacation styling' },
  { id: '021', name: '单手拿草帽', prompt: 'holding straw hat beside body, Mediterranean resort mood' },
  { id: '022', name: '双手拿草帽', prompt: 'holding hat with both hands in front naturally, relaxed resort aesthetic' },
  { id: '023', name: '单手扶帽檐', prompt: 'touching hat brim softly, summer sunlight atmosphere' },
  { id: '024', name: '风吹衬衫动作', prompt: 'shirt moving in breeze naturally, relaxed standing posture' },
  { id: '025', name: '单手扶栏杆', prompt: 'one hand resting on railing, oceanfront resort mood' },
  { id: '026', name: '双手扶栏杆', prompt: 'both hands resting on railing, looking toward ocean' },
  { id: '027', name: '阳台看海动作', prompt: 'standing on balcony, relaxed posture, luxury resort campaign' },
  { id: '028', name: '靠栏杆站姿', prompt: 'leaning casually on railing, vacation menswear photography' },
  { id: '029', name: '靠墙站姿', prompt: 'leaning naturally against wall, effortless masculine styling' },
  { id: '030', name: '单脚靠墙动作', prompt: 'one foot against wall, relaxed summer shirt aesthetic' },
  { id: '031', name: '双手背后', prompt: 'hands behind back, clean shirt silhouette display' },
  { id: '032', name: '单手背后', prompt: 'one hand behind back, relaxed masculine posture' },
  { id: '033', name: '单手扶肩', prompt: 'touching opposite shoulder naturally, casual summer styling' },
  { id: '034', name: '单手扶脖子', prompt: 'one hand resting on neck casually, relaxed vacation feeling' },
  { id: '035', name: '手插后袋', prompt: 'hands partially inside back pocket, relaxed resort mood' },
  { id: '036', name: '单手拿饮料', prompt: 'holding iced drink casually, summer holiday atmosphere' },
  { id: '037', name: '边喝饮料边走', prompt: 'walking naturally while holding drink, vacation lifestyle scene' },
  { id: '038', name: '看向太阳动作', prompt: 'looking upward toward sunlight, Mediterranean summer mood' },
  { id: '039', name: '闭眼感受阳光', prompt: 'eyes closed naturally, shirt moving softly in wind' },
  { id: '040', name: '单手扶门框', prompt: 'one hand touching doorway naturally, relaxed resort styling' },
  { id: '041', name: '靠门框动作', prompt: 'leaning casually against doorway, effortless masculine energy' },
  { id: '042', name: '站立交叉腿', prompt: 'legs crossed naturally, relaxed summer shirt campaign' },
  { id: '043', name: '单腿重心', prompt: 'weight shifted onto one leg, natural masculine silhouette' },
  { id: '044', name: '身体微前倾', prompt: 'slight forward lean, casual conversation feeling' },
  { id: '045', name: '身体微后仰', prompt: 'slight backward lean, relaxed resort atmosphere' },
  { id: '046', name: '双手扶阳台', prompt: 'hands resting naturally on balcony edge, coastal luxury mood' },
  { id: '047', name: '海边漫步动作', prompt: 'walking along shoreline naturally, shirt flowing softly' },
  { id: '048', name: '沙滩回头动作', prompt: 'walking on beach while looking back over shoulder' },
  { id: '049', name: '单手抓领口', prompt: 'holding shirt collar casually, showing neckline detail' },
  { id: '050', name: '双手抓领口', prompt: 'both hands near collar area, relaxed vacation styling' },
  { id: '051', name: '坐沙滩椅动作', prompt: 'sitting casually on beach chair, legs relaxed, one arm resting naturally, resort vacation atmosphere' },
  { id: '052', name: '沙滩椅回头动作', prompt: 'sitting on lounge chair, looking back over shoulder, summer vacation aesthetic' },
  { id: '053', name: '单手扶沙滩椅', prompt: 'one hand resting on lounge chair, relaxed linen shirt styling' },
  { id: '054', name: '双手撑椅背', prompt: 'both hands resting on chair back, relaxed masculine silhouette' },
  { id: '055', name: '坐姿扶膝', prompt: 'sitting naturally, one hand resting on knee, vacation menswear campaign' },
  { id: '056', name: '双手搭膝', prompt: 'both hands resting on knees, relaxed resort atmosphere' },
  { id: '057', name: '坐姿看远方', prompt: 'sitting casually, looking toward horizon, summer resort feeling' },
  { id: '058', name: '坐姿低头动作', prompt: 'sitting naturally, looking downward, effortless masculine mood' },
  { id: '059', name: '坐姿整理袖口', prompt: 'adjusting sleeve cuff while sitting, premium resort menswear styling' },
  { id: '060', name: '坐姿整理领口', prompt: 'touching shirt collar while seated, Mediterranean summer aesthetic' },
  { id: '061', name: '泳池边站姿', prompt: 'standing beside swimming pool, relaxed posture, luxury resort atmosphere' },
  { id: '062', name: '泳池边插兜', prompt: 'hands inside pockets, standing near pool, summer resort campaign' },
  { id: '063', name: '泳池边看水面', prompt: 'looking toward pool water, relaxed masculine energy' },
  { id: '064', name: '泳池边整理墨镜', prompt: 'touching sunglasses naturally, luxury summer styling' },
  { id: '065', name: '泳池边拿毛巾', prompt: 'holding towel casually, vacation menswear aesthetic' },
  { id: '066', name: '酒店阳台动作', prompt: 'standing on hotel balcony, looking outward, resort lifestyle photography' },
  { id: '067', name: '阳台扶栏杆', prompt: 'one hand resting on balcony railing, luxury vacation atmosphere' },
  { id: '068', name: '双手撑栏杆', prompt: 'both hands on railing, looking toward sea view' },
  { id: '069', name: '阳台转身动作', prompt: 'turning naturally on balcony, shirt moving softly' },
  { id: '070', name: '阳台回头动作', prompt: 'looking back over shoulder, Mediterranean resort mood' },
  { id: '071', name: '单手拿咖啡', prompt: 'holding coffee cup casually, morning resort lifestyle' },
  { id: '072', name: '双手拿咖啡', prompt: 'holding coffee mug with both hands, relaxed masculine energy' },
  { id: '073', name: '边喝咖啡边看海', prompt: 'drinking coffee naturally, looking toward ocean horizon' },
  { id: '074', name: '咖啡厅靠桌动作', prompt: 'leaning casually on table, summer linen shirt styling' },
  { id: '075', name: '单手扶桌面', prompt: 'one hand resting on table naturally, resort menswear photography' },
  { id: '076', name: '坐咖啡厅动作', prompt: 'sitting casually at outdoor cafe, vacation lifestyle mood' },
  { id: '077', name: '单手拿菜单', prompt: 'holding menu naturally, Mediterranean cafe atmosphere' },
  { id: '078', name: '整理手表动作', prompt: 'adjusting watch naturally, premium resort styling' },
  { id: '079', name: '查看时间动作', prompt: 'looking at wristwatch, relaxed summer aesthetic' },
  { id: '080', name: '单手整理手链', prompt: 'touching bracelet casually, vacation menswear campaign' },
  { id: '081', name: '迎风站姿', prompt: 'standing naturally in ocean breeze, shirt flowing softly' },
  { id: '082', name: '双手扶腰迎风', prompt: 'hands near waist, shirt moving in wind, Mediterranean resort mood' },
  { id: '083', name: '单手压帽子', prompt: 'holding hat against wind, summer vacation atmosphere' },
  { id: '084', name: '低头迎风动作', prompt: 'looking downward, shirt fluttering softly, coastal aesthetic' },
  { id: '085', name: '风吹开衬衫动作', prompt: 'open shirt moving naturally in breeze, relaxed masculine styling' },
  { id: '086', name: '单手抓门襟迎风', prompt: 'holding shirt placket lightly, wind effect, vacation menswear' },
  { id: '087', name: '海边站立动作', prompt: 'standing still near shoreline, relaxed masculine silhouette' },
  { id: '088', name: '海边插兜动作', prompt: 'hands inside shorts pockets, ocean backdrop, summer campaign' },
  { id: '089', name: '海边低头动作', prompt: 'looking down naturally, barefoot on sand, vacation mood' },
  { id: '090', name: '海边回头动作', prompt: 'looking back over shoulder, walking beside ocean' },
  { id: '091', name: '海边慢步动作', prompt: 'slow walking motion, relaxed body posture, shirt moving naturally' },
  { id: '092', name: '沙滩捡贝壳动作', prompt: 'slight bend forward, casual vacation lifestyle' },
  { id: '093', name: '沙滩弯腰动作', prompt: 'natural forward bend, relaxed summer styling' },
  { id: '094', name: '沙滩坐姿动作', prompt: 'sitting on beach naturally, relaxed masculine posture' },
  { id: '095', name: '单膝坐地动作', prompt: 'one knee raised, casual resort atmosphere' },
  { id: '096', name: '沙滩撑地动作', prompt: 'one hand supporting body on sand, vacation menswear campaign' },
  { id: '097', name: '岩石边站姿', prompt: 'standing near coastal rocks, Mediterranean summer aesthetic' },
  { id: '098', name: '岩石边回头动作', prompt: 'looking back naturally, shirt flowing softly' },
  { id: '099', name: '单手提鞋动作', prompt: 'holding sandals casually, walking barefoot on beach' },
  { id: '100', name: '赤脚漫步动作', prompt: 'walking barefoot naturally, resort linen shirt campaign, Mediterranean vacation lifestyle' },
];
