export interface SwimShortsPose {
  id: string;
  name: string;
  prompt: string;
}

const SWIM_SHORTS_FRAME =
  'commercial swim shorts product framing, regardless of canvas aspect ratio compose the subject from upper chest/pectorals to feet/slides, no face, no head, swim shorts occupy the central frame, waistband, drawstring, liner, hem, legs, socks and footwear visible when applicable, clean ecommerce swimwear reference framing';

export const SWIM_SHORTS_POSES: SwimShortsPose[] = [
  { id: '001', name: '正面站立', prompt: `front standing pose, cropped from chest to knees, showing full swim shorts silhouette, neutral stance, ${SWIM_SHORTS_FRAME}` },
  { id: '002', name: '背面站立', prompt: `back view standing pose, showing rear fit, swim shorts back pocket visible, ${SWIM_SHORTS_FRAME}` },
  { id: '003', name: '左侧站立', prompt: `left side profile, showing side seam and length, ${SWIM_SHORTS_FRAME}` },
  { id: '004', name: '右侧站立', prompt: `right side profile, showing side silhouette, ${SWIM_SHORTS_FRAME}` },
  { id: '005', name: '三分之二侧身', prompt: `three-quarter angle, slightly rotated body, showing front and side simultaneously, ${SWIM_SHORTS_FRAME}` },
  { id: '006', name: '单手插口袋', prompt: `one hand inside pocket, relaxed swimwear display, ${SWIM_SHORTS_FRAME}` },
  { id: '007', name: '双手插口袋', prompt: `both hands inside pockets, showing natural fit, ${SWIM_SHORTS_FRAME}` },
  { id: '008', name: '双手自然下垂', prompt: `arms relaxed, focus on waistband and fit, ${SWIM_SHORTS_FRAME}` },
  { id: '009', name: '单腿重心', prompt: `weight shifted onto one leg, showing natural drape, ${SWIM_SHORTS_FRAME}` },
  { id: '010', name: '双腿微分开', prompt: `feet shoulder width apart, clear swim shorts display, ${SWIM_SHORTS_FRAME}` },
  { id: '011', name: '拉起裤腿展示内衬', prompt: `lifting outer layer slightly, showing boxer liner, ${SWIM_SHORTS_FRAME}` },
  { id: '012', name: '拉起左裤腿', prompt: `showing compression liner, lifting left leg opening, ${SWIM_SHORTS_FRAME}` },
  { id: '013', name: '拉起右裤腿', prompt: `showing inner shorts structure, lifting right leg opening, ${SWIM_SHORTS_FRAME}` },
  { id: '014', name: '双手拉裤腰', prompt: `stretching waistband outward, showing elasticity, ${SWIM_SHORTS_FRAME}` },
  { id: '015', name: '单手拉裤腰', prompt: `demonstrating stretch waistband with one hand, ${SWIM_SHORTS_FRAME}` },
  { id: '016', name: '调整抽绳', prompt: `adjusting drawstring naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '017', name: '系抽绳动作', prompt: `tying waistband drawstring, ${SWIM_SHORTS_FRAME}` },
  { id: '018', name: '手扶腰头', prompt: `showing waistband construction, hand resting on waistband, ${SWIM_SHORTS_FRAME}` },
  { id: '019', name: '展示口袋动作', prompt: `hand partially inside pocket, ${SWIM_SHORTS_FRAME}` },
  { id: '020', name: '拉开口袋', prompt: `showing pocket depth, hand opening pocket, ${SWIM_SHORTS_FRAME}` },
  { id: '021', name: '海边站姿', prompt: `standing near shoreline, cropped waist-down focus, ${SWIM_SHORTS_FRAME}` },
  { id: '022', name: '沙滩漫步', prompt: `walking naturally on beach, ${SWIM_SHORTS_FRAME}` },
  { id: '023', name: '赤脚站沙滩', prompt: `barefoot on sand, ${SWIM_SHORTS_FRAME}` },
  { id: '024', name: '沙滩回头', prompt: `walking away, body slightly turned, ${SWIM_SHORTS_FRAME}` },
  { id: '025', name: '海浪边站立', prompt: `water touching ankles, showing swim shorts naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '026', name: '海边插兜', prompt: `hands inside pockets, beach lifestyle, ${SWIM_SHORTS_FRAME}` },
  { id: '027', name: '海边低头', prompt: `looking downward, focus on shorts, ${SWIM_SHORTS_FRAME}` },
  { id: '028', name: '海边行走抓拍', prompt: `candid walking motion, beach background, ${SWIM_SHORTS_FRAME}` },
  { id: '029', name: '单手拿拖鞋', prompt: `holding sandals casually, ${SWIM_SHORTS_FRAME}` },
  { id: '030', name: '沙滩整理裤腰', prompt: `adjusting drawstring on beach, ${SWIM_SHORTS_FRAME}` },
  { id: '031', name: '泳池边站姿', prompt: `standing beside pool, ${SWIM_SHORTS_FRAME}` },
  { id: '032', name: '泳池边插兜', prompt: `hands inside pockets beside pool, ${SWIM_SHORTS_FRAME}` },
  { id: '033', name: '泳池边坐姿', prompt: `sitting on pool edge, swim shorts fit visible, ${SWIM_SHORTS_FRAME}` },
  { id: '034', name: '泳池边扶膝', prompt: `hands resting on knees beside pool, ${SWIM_SHORTS_FRAME}` },
  { id: '035', name: '泳池边回头', prompt: `looking back naturally beside pool, ${SWIM_SHORTS_FRAME}` },
  { id: '036', name: '泳池边起身', prompt: `standing from pool edge, ${SWIM_SHORTS_FRAME}` },
  { id: '037', name: '泳池边行走', prompt: `walking beside pool, ${SWIM_SHORTS_FRAME}` },
  { id: '038', name: '从泳池出来', prompt: `stepping out of pool, water dripping naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '039', name: '湿身泳裤展示', prompt: `wet fabric texture visible, ${SWIM_SHORTS_FRAME}` },
  { id: '040', name: '调整泳裤动作', prompt: `pulling waistband naturally, poolside swimwear display, ${SWIM_SHORTS_FRAME}` },
  { id: '041', name: '慢跑动作', prompt: `light jogging motion, ${SWIM_SHORTS_FRAME}` },
  { id: '042', name: '跑步起步', prompt: `starting running motion, ${SWIM_SHORTS_FRAME}` },
  { id: '043', name: '沙滩奔跑', prompt: `running barefoot on beach, ${SWIM_SHORTS_FRAME}` },
  { id: '044', name: '侧面跑步', prompt: `side running profile, ${SWIM_SHORTS_FRAME}` },
  { id: '045', name: '行走抓拍', prompt: `natural walking movement, ${SWIM_SHORTS_FRAME}` },
  { id: '046', name: '双手叉腰', prompt: `athletic stance, both hands on waist, ${SWIM_SHORTS_FRAME}` },
  { id: '047', name: '单手扶腰', prompt: `relaxed athletic posture, one hand on waist, ${SWIM_SHORTS_FRAME}` },
  { id: '048', name: '热身动作', prompt: `stretching legs, athletic swim shorts display, ${SWIM_SHORTS_FRAME}` },
  { id: '049', name: '弯腰动作', prompt: `slight forward bend, ${SWIM_SHORTS_FRAME}` },
  { id: '050', name: '擦汗动作', prompt: `holding towel naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '051', name: '正面展示', prompt: `front fit display, ${SWIM_SHORTS_FRAME}` },
  { id: '052', name: '背面展示', prompt: `rear fit display, ${SWIM_SHORTS_FRAME}` },
  { id: '053', name: '左侧展示', prompt: `left profile, ${SWIM_SHORTS_FRAME}` },
  { id: '054', name: '右侧展示', prompt: `right profile, ${SWIM_SHORTS_FRAME}` },
  { id: '055', name: '三分之二角度', prompt: `three-quarter angle, ${SWIM_SHORTS_FRAME}` },
  { id: '056', name: '拉内衬', prompt: `showing compression liner, ${SWIM_SHORTS_FRAME}` },
  { id: '057', name: '展示抽绳', prompt: `showing drawstring, ${SWIM_SHORTS_FRAME}` },
  { id: '058', name: '展示口袋', prompt: `showing pocket depth, ${SWIM_SHORTS_FRAME}` },
  { id: '059', name: '展示裤长', prompt: `showing inseam length, ${SWIM_SHORTS_FRAME}` },
  { id: '060', name: '展示面料', prompt: `showing fabric texture, ${SWIM_SHORTS_FRAME}` },
  { id: '061', name: '左手拉起裤腿', prompt: `lifting left outer layer, revealing compression liner, showing inner shorts construction, ${SWIM_SHORTS_FRAME}` },
  { id: '062', name: '右手拉起裤腿', prompt: `lifting right outer layer, displaying boxer liner detail, ${SWIM_SHORTS_FRAME}` },
  { id: '063', name: '双手拉裤腿', prompt: `holding both sides of outer shorts, showing liner coverage, ${SWIM_SHORTS_FRAME}` },
  { id: '064', name: '拉起前侧裤腿', prompt: `lifting front section of swim shorts, revealing inner liner, ${SWIM_SHORTS_FRAME}` },
  { id: '065', name: '拉起侧面裤腿', prompt: `revealing side liner structure, showing layering design, ${SWIM_SHORTS_FRAME}` },
  { id: '066', name: '单手拉腰头', prompt: `pulling waistband outward, demonstrating elasticity, ${SWIM_SHORTS_FRAME}` },
  { id: '067', name: '双手拉腰头', prompt: `stretching waistband with both hands, showing comfort fit, ${SWIM_SHORTS_FRAME}` },
  { id: '068', name: '单手调整抽绳', prompt: `adjusting drawstring casually, focus on waistband details, ${SWIM_SHORTS_FRAME}` },
  { id: '069', name: '双手系抽绳', prompt: `tying waistband drawcord, showing front construction, ${SWIM_SHORTS_FRAME}` },
  { id: '070', name: '抽绳特写动作', prompt: `hands holding drawstring, focus on waistband craftsmanship, ${SWIM_SHORTS_FRAME}` },
  { id: '071', name: '单手展示口袋', prompt: `hand partially inside pocket, showing storage capacity, ${SWIM_SHORTS_FRAME}` },
  { id: '072', name: '双手展示口袋', prompt: `both hands opening pockets, showing pocket depth, ${SWIM_SHORTS_FRAME}` },
  { id: '073', name: '拉出口袋布', prompt: `pulling pocket lining outward, demonstrating pocket size, ${SWIM_SHORTS_FRAME}` },
  { id: '074', name: '单手展示内衬', prompt: `holding compression liner edge, showing breathable material, ${SWIM_SHORTS_FRAME}` },
  { id: '075', name: '双手展示内衬', prompt: `stretching liner slightly, showing flexibility, ${SWIM_SHORTS_FRAME}` },
  { id: '076', name: '展示裤长', prompt: `standing naturally, hands down, focus on inseam length, ${SWIM_SHORTS_FRAME}` },
  { id: '077', name: '展示侧开叉', prompt: `side angle, highlighting side slit detail, ${SWIM_SHORTS_FRAME}` },
  { id: '078', name: '展示后袋', prompt: `back view, hand touching rear pocket, ${SWIM_SHORTS_FRAME}` },
  { id: '079', name: '展示后腰松紧', prompt: `back waistband stretch demonstration, ${SWIM_SHORTS_FRAME}` },
  { id: '080', name: '展示速干面料', prompt: `holding fabric lightly, showing lightweight texture, ${SWIM_SHORTS_FRAME}` },
  { id: '081', name: '展示弹力面料', prompt: `pulling fabric gently, showing stretch capability, ${SWIM_SHORTS_FRAME}` },
  { id: '082', name: '展示透气孔', prompt: `hand indicating mesh ventilation area, ${SWIM_SHORTS_FRAME}` },
  { id: '083', name: '展示防磨内衬', prompt: `lifting outer layer, showing anti-chafing compression liner, ${SWIM_SHORTS_FRAME}` },
  { id: '084', name: '展示双层结构', prompt: `revealing inner and outer layers simultaneously, ${SWIM_SHORTS_FRAME}` },
  { id: '085', name: '展示内衬裤腿长度', prompt: `showing liner extension length, ${SWIM_SHORTS_FRAME}` },
  { id: '086', name: '展示内衬侧袋', prompt: `revealing hidden phone pocket inside liner, ${SWIM_SHORTS_FRAME}` },
  { id: '087', name: '单手拿手机展示口袋', prompt: `holding phone near liner pocket, ${SWIM_SHORTS_FRAME}` },
  { id: '088', name: '手机放入口袋动作', prompt: `placing phone inside liner pocket, ${SWIM_SHORTS_FRAME}` },
  { id: '089', name: '展示钥匙口袋', prompt: `holding keys near zipper pocket, ${SWIM_SHORTS_FRAME}` },
  { id: '090', name: '展示拉链口袋', prompt: `opening zipper pocket naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '091', name: '展示网布内衬', prompt: `showing mesh liner construction, ${SWIM_SHORTS_FRAME}` },
  { id: '092', name: '展示裤腰厚度', prompt: `pinching waistband material, ${SWIM_SHORTS_FRAME}` },
  { id: '093', name: '展示腰绳细节', prompt: `holding drawstring ends naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '094', name: '展示缝线细节', prompt: `hands highlighting seam construction, ${SWIM_SHORTS_FRAME}` },
  { id: '095', name: '展示裤脚开口', prompt: `holding hem edge, showing leg opening, ${SWIM_SHORTS_FRAME}` },
  { id: '096', name: '展示内衬包裹感', prompt: `hands stretching liner slightly, ${SWIM_SHORTS_FRAME}` },
  { id: '097', name: '展示运动功能', prompt: `athletic stance, highlighting liner support, ${SWIM_SHORTS_FRAME}` },
  { id: '098', name: '展示训练适用性', prompt: `ready-to-run posture, focus on shorts fit, ${SWIM_SHORTS_FRAME}` },
  { id: '099', name: '展示游泳适用性', prompt: `wet swim shorts, compression liner visible, ${SWIM_SHORTS_FRAME}` },
  { id: '100', name: '展示综合卖点', prompt: `one hand pulling liner, other hand adjusting waistband, showing full shorts construction, ${SWIM_SHORTS_FRAME}` },
  { id: '101', name: '海边正面站立', prompt: `standing on beach, cropped from chest to knees, focus on swim shorts silhouette, ${SWIM_SHORTS_FRAME}` },
  { id: '102', name: '海边插兜', prompt: `hands inside pockets, ocean background blurred, ${SWIM_SHORTS_FRAME}` },
  { id: '103', name: '海边低头', prompt: `looking downward, showing waistband and drawstring, ${SWIM_SHORTS_FRAME}` },
  { id: '104', name: '海边回头', prompt: `walking along shoreline, looking back naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '105', name: '海边漫步', prompt: `barefoot walking, swim shorts moving naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '106', name: '海边踩浪', prompt: `standing with water touching ankles, ${SWIM_SHORTS_FRAME}` },
  { id: '107', name: '海边整理裤腰', prompt: `adjusting drawstring naturally, ${SWIM_SHORTS_FRAME}` },
  { id: '108', name: '海边拿拖鞋', prompt: `holding sandals casually, ${SWIM_SHORTS_FRAME}` },
  { id: '109', name: '海边拿冲浪板', prompt: `holding surfboard beside body, ${SWIM_SHORTS_FRAME}` },
  { id: '110', name: '靠冲浪板站姿', prompt: `leaning naturally against surfboard, ${SWIM_SHORTS_FRAME}` },
  { id: '111', name: '海边扶腰', prompt: `one hand on waist, beach swimwear display, ${SWIM_SHORTS_FRAME}` },
  { id: '112', name: '海边双手叉腰', prompt: `athletic beach stance, both hands on waist, ${SWIM_SHORTS_FRAME}` },
  { id: '113', name: '海边低头看裤子', prompt: `looking at swim shorts detail, ${SWIM_SHORTS_FRAME}` },
  { id: '114', name: '海边湿身展示', prompt: `wet fabric texture visible, ${SWIM_SHORTS_FRAME}` },
  { id: '115', name: '海边迎风站姿', prompt: `shorts moving slightly in wind, ${SWIM_SHORTS_FRAME}` },
  { id: '116', name: '海边慢跑', prompt: `light jogging along shoreline, ${SWIM_SHORTS_FRAME}` },
  { id: '117', name: '海边坐沙滩椅', prompt: `relaxed beach chair pose, ${SWIM_SHORTS_FRAME}` },
  { id: '118', name: '海边扶膝', prompt: `hands resting on knees, ${SWIM_SHORTS_FRAME}` },
  { id: '119', name: '海边坐地', prompt: `sitting casually on sand, ${SWIM_SHORTS_FRAME}` },
  { id: '120', name: '海边单膝坐姿', prompt: `one knee raised, focus on shorts fit, ${SWIM_SHORTS_FRAME}` }
];
