export interface MensKnitPose {
  id: string;
  name: string;
  prompt: string;
}

export const MENS_KNIT_POSES: MensKnitPose[] = [
  { id: '001', name: '微侧身站姿', prompt: 'three-quarter body angle, relaxed shoulders, one foot slightly forward, textured knit polo, resort menswear campaign' },
  { id: '002', name: '单手插短裤口袋', prompt: 'one hand inside shorts pocket, relaxed posture, summer knit polo styling' },
  { id: '003', name: '双手插口袋', prompt: 'both hands inside pockets, effortless masculine energy, coastal vacation mood' },
  { id: '004', name: '单腿重心', prompt: 'weight shifted onto one leg, natural masculine silhouette, resort knitwear aesthetic' },
  { id: '005', name: '交叉脚站姿', prompt: 'legs crossed naturally, relaxed body posture, old money summer mood' },
  { id: '006', name: '单手扶腰', prompt: 'one hand on waist, showing polo fit naturally' },
  { id: '007', name: '双手扶腰', prompt: 'hands near waist, confident resort menswear styling' },
  { id: '008', name: '单手抓衣摆', prompt: 'holding polo hem casually, showing fabric drape' },
  { id: '009', name: '双手抓衣摆', prompt: 'holding both sides of polo hem, showing knit structure' },
  { id: '010', name: '单手抓领口', prompt: 'touching polo collar naturally, showing neckline detail' },
  { id: '011', name: '双手抓领口', prompt: 'holding collar area casually, showing open neck styling' },
  { id: '012', name: '调整领口动作', prompt: 'adjusting polo collar, premium knitwear campaign' },
  { id: '013', name: '解开纽扣动作', prompt: 'opening top button naturally, Mediterranean summer aesthetic' },
  { id: '014', name: '整理袖口动作', prompt: 'adjusting sleeve cuff, showing knit texture' },
  { id: '015', name: '单手扶后颈', prompt: 'one hand touching neck, summer vacation mood' },
  { id: '016', name: '双手背后', prompt: 'hands behind back, clean silhouette display' },
  { id: '017', name: '单手背后', prompt: 'one hand behind body, relaxed masculine posture' },
  { id: '018', name: '看向远方', prompt: 'looking toward horizon, coastal resort atmosphere' },
  { id: '019', name: '低头动作', prompt: 'looking downward naturally, effortless summer styling' },
  { id: '020', name: '回头动作', prompt: 'looking back over shoulder, vacation menswear campaign' },
  { id: '021', name: '回头微笑', prompt: 'subtle smile, looking back naturally' },
  { id: '022', name: '闭眼晒太阳', prompt: 'eyes closed, warm sunlight, Mediterranean vacation mood' },
  { id: '023', name: '迎风站姿', prompt: 'shirt moving softly in breeze, relaxed masculine energy' },
  { id: '024', name: '单手压帽檐', prompt: 'holding hat brim naturally, summer knit polo aesthetic' },
  { id: '025', name: '单手拿墨镜', prompt: 'holding sunglasses casually, luxury resort styling' },
  { id: '026', name: '单手扶栏杆', prompt: 'one hand resting on railing, luxury yacht atmosphere' },
  { id: '027', name: '双手扶栏杆', prompt: 'both hands on railing, looking toward ocean' },
  { id: '028', name: '靠栏杆站姿', prompt: 'leaning casually on railing, old money summer aesthetic' },
  { id: '029', name: '阳台看海', prompt: 'standing on balcony, Mediterranean resort mood' },
  { id: '030', name: '阳台回头', prompt: 'looking back naturally, luxury resort campaign' },
  { id: '031', name: '单手拿咖啡', prompt: 'holding coffee cup casually, summer morning atmosphere' },
  { id: '032', name: '双手拿咖啡', prompt: 'holding coffee with both hands, relaxed masculine mood' },
  { id: '033', name: '边喝咖啡边看海', prompt: 'drinking coffee naturally, looking toward ocean' },
  { id: '034', name: '看手表动作', prompt: 'looking at wristwatch, old money styling' },
  { id: '035', name: '整理手表动作', prompt: 'adjusting watch naturally, premium resort menswear' },
  { id: '036', name: '单手扶桌面', prompt: 'one hand resting on table, vacation cafe atmosphere' },
  { id: '037', name: '坐咖啡厅动作', prompt: 'sitting casually outdoors, Mediterranean summer mood' },
  { id: '038', name: '单手拿菜单', prompt: 'holding menu naturally, resort cafe aesthetic' },
  { id: '039', name: '单手扶椅背', prompt: 'one hand on chair back, relaxed masculine posture' },
  { id: '040', name: '双手撑椅背', prompt: 'both hands resting on chair, luxury vacation styling' },
  { id: '041', name: '靠墙站姿', prompt: 'leaning naturally against wall, old money summer campaign' },
  { id: '042', name: '单脚靠墙', prompt: 'one foot against wall, relaxed masculine silhouette' },
  { id: '043', name: '单手插兜看海', prompt: 'one hand in pocket, looking toward ocean' },
  { id: '044', name: '双手插兜看海', prompt: 'both hands in pockets, Mediterranean vacation mood' },
  { id: '045', name: '身体微后仰', prompt: 'slight backward lean, relaxed confidence' },
  { id: '046', name: '身体微前倾', prompt: 'slight forward lean, casual conversation feeling' },
  { id: '047', name: '单手扶脖子', prompt: 'one hand touching neck, warm summer atmosphere' },
  { id: '048', name: '单手扶肩', prompt: 'touching opposite shoulder, relaxed knit polo styling' },
  { id: '049', name: '双手交叉身前', prompt: 'hands loosely crossed, showing polo texture' },
  { id: '050', name: '单手拿草帽', prompt: 'holding straw hat naturally, resort menswear campaign' },
  { id: '051', name: '双手扶游艇栏杆', prompt: 'both hands resting naturally on yacht railing, ocean breeze, luxury summer vacation atmosphere' },
  { id: '052', name: '单手扶游艇栏杆', prompt: 'one hand resting on yacht railing, relaxed masculine posture, old money aesthetic' },
  { id: '053', name: '看海平线动作', prompt: 'looking toward ocean horizon, relaxed shoulders, summer knit polo campaign' },
  { id: '054', name: '游艇甲板行走', prompt: 'walking naturally on yacht deck, shirt moving softly in wind, luxury resort menswear' },
  { id: '055', name: '边走边看海', prompt: 'walking casually, looking toward ocean, Mediterranean summer mood' },
  { id: '056', name: '单手拿香槟杯', prompt: 'holding champagne glass naturally, luxury vacation styling' },
  { id: '057', name: '双手扶腰看海', prompt: 'hands resting near waist, looking toward ocean horizon' },
  { id: '058', name: '单手插口袋看海', prompt: 'one hand in pocket, standing on yacht deck, coastal luxury atmosphere' },
  { id: '059', name: '迎风整理领口', prompt: 'touching knit polo collar, ocean breeze movement' },
  { id: '060', name: '单手压帽檐迎风', prompt: 'holding hat brim, Mediterranean yacht aesthetic' },
  { id: '061', name: '单手拿墨镜看海', prompt: 'holding sunglasses casually, luxury summer campaign' },
  { id: '062', name: '整理墨镜动作', prompt: 'adjusting sunglasses naturally, old money menswear styling' },
  { id: '063', name: '单手扶后颈看海', prompt: 'one hand touching neck, relaxed luxury vacation mood' },
  { id: '064', name: '单手抓门襟迎风', prompt: 'holding shirt placket lightly, fabric moving in breeze' },
  { id: '065', name: '低头迎风动作', prompt: 'looking downward, shirt fluttering naturally' },
  { id: '066', name: '双手背后看海', prompt: 'hands behind back, relaxed wealthy traveler aesthetic' },
  { id: '067', name: '单手背后站姿', prompt: 'one hand behind body, luxury coastal atmosphere' },
  { id: '068', name: '回头看海动作', prompt: 'body facing ocean, looking back over shoulder' },
  { id: '069', name: '回头微笑动作', prompt: 'looking back with subtle smile, summer yacht campaign' },
  { id: '070', name: '身体微后仰晒太阳', prompt: 'slight backward lean, eyes closed, warm sunlight' },
  { id: '071', name: '闭眼感受海风', prompt: 'eyes closed naturally, ocean breeze moving shirt' },
  { id: '072', name: '单脚交叉站姿', prompt: 'legs crossed naturally, luxury summer silhouette' },
  { id: '073', name: '双手插兜站甲板', prompt: 'both hands in pockets, standing on yacht deck' },
  { id: '074', name: '单手扶栏杆回头', prompt: 'one hand on railing, looking back casually' },
  { id: '075', name: '双手撑栏杆俯瞰海面', prompt: 'both hands on railing, looking downward toward water, luxury yacht lifestyle' },
  { id: '076', name: '地中海街道漫步', prompt: 'walking naturally through mediterranean street, relaxed knit polo styling' },
  { id: '077', name: '石墙边站姿', prompt: 'standing beside white stone wall, Mediterranean vacation atmosphere' },
  { id: '078', name: '靠白墙站姿', prompt: 'leaning naturally against white wall, summer resort aesthetic' },
  { id: '079', name: '单手插兜漫步', prompt: 'walking casually, one hand in pocket, Mediterranean resort campaign' },
  { id: '080', name: '双手插兜漫步', prompt: 'both hands in pockets, relaxed masculine energy' },
  { id: '081', name: '单手拿咖啡漫步', prompt: 'holding coffee while walking, European summer mood' },
  { id: '082', name: '单手拿冰饮动作', prompt: 'holding iced drink casually, vacation lifestyle campaign' },
  { id: '083', name: '咖啡厅门口站姿', prompt: 'standing outside cafe naturally, Mediterranean atmosphere' },
  { id: '084', name: '坐咖啡厅看远方', prompt: 'sitting casually, looking toward street' },
  { id: '085', name: '单手扶桌面喝咖啡', prompt: 'one hand on table, holding coffee naturally' },
  { id: '086', name: '单手整理袖口', prompt: 'adjusting sleeve naturally, showing knit texture' },
  { id: '087', name: '整理领口动作', prompt: 'touching collar casually, premium summer knitwear' },
  { id: '088', name: '单手抓衣摆', prompt: 'holding hem naturally, showing fabric drape' },
  { id: '089', name: '双手抓衣摆', prompt: 'holding both sides of polo hem, showing fit' },
  { id: '090', name: '单手扶腰站姿', prompt: 'one hand on waist, Mediterranean menswear campaign' },
  { id: '091', name: '双手扶腰站姿', prompt: 'hands near waist, vacation confidence mood' },
  { id: '092', name: '回头微笑动作', prompt: 'looking back with soft smile, European summer atmosphere' },
  { id: '093', name: '单手扶门框', prompt: 'one hand touching doorway, Mediterranean architecture' },
  { id: '094', name: '靠门框站姿', prompt: 'leaning casually against doorway, resort menswear styling' },
  { id: '095', name: '看向远方动作', prompt: 'looking toward horizon, relaxed summer energy' },
  { id: '096', name: '闭眼晒太阳动作', prompt: 'eyes closed naturally, warm sunlight hitting face' },
  { id: '097', name: '单手拿草帽动作', prompt: 'holding straw hat beside body, vacation campaign aesthetic' },
  { id: '098', name: '单手压帽檐动作', prompt: 'touching hat brim naturally, summer resort styling' },
  { id: '099', name: '迎风站姿', prompt: 'shirt moving softly, Mediterranean coastal breeze' },
  { id: '100', name: '行走回头动作', prompt: 'walking naturally, looking back softly, luxury summer knit polo campaign' },
];
