export interface MensPantsPose {
  id: string;
  name: string;
  prompt: string;
}

const MENS_PANTS_FRAME =
  'commercial mens pants product display, default crop is lower-torso/waist-to-shoes and not full-body unless the user explicitly requests full-body, keep pants as the central product focus, show waistband, belt loops or belt, pockets, side seams, pant leg drape, inseam length, hem break, fit, fabric folds and silhouette clearly, realistic menswear proportions, premium SHEIN menswear campaign styling';

const withFrame = (prompt: string) => `${prompt}, ${MENS_PANTS_FRAME}`;

export const MENS_PANTS_POSES: MensPantsPose[] = [
  { id: '001', name: '正面站立', prompt: withFrame('front standing pose, feet shoulder-width apart, showing full pants silhouette') },
  { id: '002', name: '微侧身站立', prompt: withFrame('three-quarter body angle, showing front and side fit') },
  { id: '003', name: '左侧展示', prompt: withFrame('left side profile, showing pant leg drape') },
  { id: '004', name: '右侧展示', prompt: withFrame('right side profile, showing silhouette') },
  { id: '005', name: '背面展示', prompt: withFrame('back view, showing rear fit') },
  { id: '006', name: '单腿重心', prompt: withFrame('weight shifted onto one leg, relaxed pants drape') },
  { id: '007', name: '双腿微分开', prompt: withFrame('natural stance, showing straight-leg shape') },
  { id: '008', name: '单脚前探', prompt: withFrame('one foot slightly forward, elongating leg line') },
  { id: '009', name: '单脚后撤', prompt: withFrame('one foot behind naturally') },
  { id: '010', name: '双腿交叉站姿', prompt: withFrame('crossed leg stance, editorial menswear mood') },
  { id: '011', name: '单手插裤袋', prompt: withFrame('one hand inside pocket, casual menswear styling') },
  { id: '012', name: '双手插裤袋', prompt: withFrame('both hands inside pockets, relaxed silhouette') },
  { id: '013', name: '拇指挂裤袋', prompt: withFrame('thumb hooked inside waistband') },
  { id: '014', name: '单手扶腰', prompt: withFrame('one hand resting on waist') },
  { id: '015', name: '双手扶腰', prompt: withFrame('hands on waist, showing trouser fit') },
  { id: '016', name: '单手扶裤腰', prompt: withFrame('touching waistband naturally') },
  { id: '017', name: '双手扶裤腰', prompt: withFrame('holding waistband casually') },
  { id: '018', name: '整理腰带动作', prompt: withFrame('adjusting belt naturally') },
  { id: '019', name: '调整裤腰动作', prompt: withFrame('straightening waistband') },
  { id: '020', name: '展示腰头动作', prompt: withFrame('highlighting waistband construction') },
  { id: '021', name: '单手抓裤缝', prompt: withFrame('holding side seam lightly') },
  { id: '022', name: '单手抓裤腿', prompt: withFrame('holding pant leg naturally') },
  { id: '023', name: '双手抓裤腿', prompt: withFrame('holding both pant legs lightly') },
  { id: '024', name: '整理裤脚动作', prompt: withFrame('adjusting hem naturally') },
  { id: '025', name: '展示裤长动作', prompt: withFrame('standing straight, focus on inseam length') },
  { id: '026', name: '单手扶大腿', prompt: withFrame('hand resting on thigh') },
  { id: '027', name: '双手自然下垂', prompt: withFrame('arms relaxed naturally') },
  { id: '028', name: '双手背后', prompt: withFrame('hands behind back') },
  { id: '029', name: '单手背后', prompt: withFrame('one hand behind body') },
  { id: '030', name: '双臂抱胸', prompt: withFrame('arms crossed, minimal menswear styling') },
  { id: '031', name: '低头看裤子', prompt: withFrame('looking downward at pants') },
  { id: '032', name: '看远方动作', prompt: withFrame('looking into distance') },
  { id: '033', name: '回头动作', prompt: withFrame('looking back over shoulder') },
  { id: '034', name: '回头微笑', prompt: withFrame('subtle smile, looking back') },
  { id: '035', name: '身体微前倾', prompt: withFrame('slight forward lean') },
  { id: '036', name: '身体微后仰', prompt: withFrame('slight backward lean') },
  { id: '037', name: '靠墙站姿', prompt: withFrame('leaning casually against wall') },
  { id: '038', name: '单肩靠墙', prompt: withFrame('one shoulder touching wall') },
  { id: '039', name: '单脚靠墙', prompt: withFrame('one foot against wall') },
  { id: '040', name: '双手插袋靠墙', prompt: withFrame('hands in pockets, leaning naturally') },
  { id: '041', name: '单手扶墙', prompt: withFrame('touching wall lightly') },
  { id: '042', name: '靠栏杆站姿', prompt: withFrame('leaning on railing') },
  { id: '043', name: '单手扶栏杆', prompt: withFrame('one hand resting on railing') },
  { id: '044', name: '双手扶栏杆', prompt: withFrame('both hands resting naturally') },
  { id: '045', name: '单手拿手机', prompt: withFrame('holding smartphone casually') },
  { id: '046', name: '查看手机动作', prompt: withFrame('looking at phone naturally') },
  { id: '047', name: '单手拿咖啡', prompt: withFrame('holding coffee cup casually') },
  { id: '048', name: '单手拿饮料', prompt: withFrame('holding iced drink') },
  { id: '049', name: '单手拿钥匙', prompt: withFrame('holding keys casually') },
  { id: '050', name: '单手拿耳机', prompt: withFrame('holding headphones naturally') },
  { id: '051', name: '慢步行走', prompt: withFrame('slow walking motion, pants moving naturally') },
  { id: '052', name: '行走抓拍', prompt: withFrame('candid walking shot') },
  { id: '053', name: '单手插袋行走', prompt: withFrame('walking with one hand in pocket') },
  { id: '054', name: '双手插袋行走', prompt: withFrame('walking with both hands in pockets') },
  { id: '055', name: '行走回头', prompt: withFrame('looking back while walking') },
  { id: '056', name: '行走低头', prompt: withFrame('looking downward while moving') },
  { id: '057', name: '行走看远方', prompt: withFrame('looking ahead naturally') },
  { id: '058', name: '行走整理腰带', prompt: withFrame('adjusting belt while walking') },
  { id: '059', name: '行走扶腰', prompt: withFrame('one hand on waist while moving') },
  { id: '060', name: '行走拿手机', prompt: withFrame('walking with smartphone') },
  { id: '061', name: '大步行走', prompt: withFrame('long runway-inspired stride') },
  { id: '062', name: '小步慢走', prompt: withFrame('relaxed casual movement') },
  { id: '063', name: '交叉步行走', prompt: withFrame('cross-step walking motion') },
  { id: '064', name: '风吹裤腿动作', prompt: withFrame('fabric moving naturally') },
  { id: '065', name: '裤腿摆动动作', prompt: withFrame('pants moving during walk') },
  { id: '066', name: '坐姿扶膝', prompt: withFrame('hands resting on knees') },
  { id: '067', name: '坐姿交叉腿', prompt: withFrame('crossed legs seated pose') },
  { id: '068', name: '坐姿插袋', prompt: withFrame('hands inside pockets seated') },
  { id: '069', name: '坐姿低头', prompt: withFrame('looking downward seated') },
  { id: '070', name: '台阶坐姿', prompt: withFrame('sitting on stairs naturally') },
  { id: '071', name: '长椅坐姿', prompt: withFrame('sitting casually on bench') },
  { id: '072', name: '靠椅背坐姿', prompt: withFrame('leaning back into chair') },
  { id: '073', name: '单腿伸展坐姿', prompt: withFrame('one leg extended naturally') },
  { id: '074', name: '单手撑身体', prompt: withFrame('one arm supporting body') },
  { id: '075', name: '双手扶膝坐姿', prompt: withFrame('both hands resting on knees') },
  { id: '076', name: '坐姿整理裤脚', prompt: withFrame('adjusting hem while seated') },
  { id: '077', name: '坐姿整理腰带', prompt: withFrame('adjusting belt naturally') },
  { id: '078', name: '单膝抬高坐姿', prompt: withFrame('one knee raised, showing pant folds') },
  { id: '079', name: '双脚前伸坐姿', prompt: withFrame('legs stretched forward') },
  { id: '080', name: '坐姿看远方', prompt: withFrame('looking into distance') },
  { id: '081', name: '工装裤插袋动作', prompt: withFrame('hands inside cargo pockets') },
  { id: '082', name: '展示侧袋动作', prompt: withFrame('showing cargo pocket details') },
  { id: '083', name: '展示拉链袋动作', prompt: withFrame('opening utility pocket') },
  { id: '084', name: '展示工装结构', prompt: withFrame('highlighting cargo construction') },
  { id: '085', name: '展示宽松裤型', prompt: withFrame('showing wide-leg silhouette') },
  { id: '086', name: '展示直筒裤型', prompt: withFrame('showing straight-leg fit') },
  { id: '087', name: '展示锥形裤型', prompt: withFrame('showing tapered silhouette') },
  { id: '088', name: '展示亚麻裤垂感', prompt: withFrame('highlighting linen drape') },
  { id: '089', name: '展示褶皱裤型', prompt: withFrame('showing natural fabric folds') },
  { id: '090', name: '展示高腰结构', prompt: withFrame('highlighting waistband height') },
  { id: '091', name: '展示裤脚堆积感', prompt: withFrame('showing stacking at hem') },
  { id: '092', name: '展示裤脚长度', prompt: withFrame('focus on hem break') },
  { id: '093', name: '展示运动裤版型', prompt: withFrame('athletic fit stance') },
  { id: '094', name: '展示休闲裤版型', prompt: withFrame('relaxed casual fit') },
  { id: '095', name: '展示工装裤版型', prompt: withFrame('utility cargo fit') },
  { id: '096', name: '展示宽腿裤版型', prompt: withFrame('wide-leg silhouette emphasis') },
  { id: '097', name: '展示老钱风裤型', prompt: withFrame('old money relaxed trouser stance') },
  { id: '098', name: '展示度假裤型', prompt: withFrame('resort linen pants styling') },
  { id: '099', name: '展示街头裤型', prompt: withFrame('streetwear trouser aesthetic') },
  { id: '100', name: 'Hero pants pose', prompt: withFrame('Hero pants pose, relaxed confidence, showing full trouser silhouette, premium SHEIN menswear campaign') },
];
