export interface SleepwearPose {
  id: string;
  name: string;
  prompt: string;
}

export const SLEEPWEAR_POSES: SleepwearPose[] = [
  { id: '021', name: '床上自然侧坐', prompt: 'sitting sideways naturally on bed, one leg bent softly, relaxed pajama folds, cozy feminine posture, soft morning light, realistic bedding wrinkles' },
  { id: '022', name: '床上双腿伸直坐姿', prompt: 'sitting on bed with legs extended naturally, relaxed upper body posture, oversized pajama drape, cozy homewear aesthetic' },
  { id: '023', name: '床头靠坐动作', prompt: 'leaning comfortably against bed headboard, knees slightly bent, relaxed sleepy expression, realistic pajama folds and bedding texture' },
  { id: '024', name: '被窝探头动作', prompt: 'upper body slightly outside blanket, messy morning hair, cozy sleepy atmosphere, soft warm bedroom lighting' },
  { id: '025', name: '单手撑床动作', prompt: 'one hand supporting body on bed, relaxed torso twist, natural pajama wrinkles, lifestyle sleepwear photography' },
  { id: '026', name: '抱腿窝床动作', prompt: 'hugging legs softly while sitting on bed, oversized sleepwear naturally folded, emotional cozy morning mood' },
  { id: '027', name: '侧卧撑头动作', prompt: 'lying sideways with one hand supporting head, relaxed feminine silhouette, soft pajama drape, cozy bedroom aesthetic' },
  { id: '028', name: '仰躺伸展动作', prompt: 'lying on back naturally stretching arms upward, relaxed sleepy morning vibe, realistic pajama folds' },
  { id: '029', name: '趴床踢腿动作', prompt: 'lying on stomach on bed, legs bent upward playfully, cozy youthful pajama feeling, soft bedding folds' },
  { id: '030', name: '被子包裹动作', prompt: 'wrapped softly in blanket with pajamas partially visible, intimate cozy atmosphere, realistic home lifestyle feeling' },
  { id: '031', name: '沙发抱枕动作', prompt: 'hugging pillow naturally while sitting on sofa, cozy relaxed posture, oversized pajama wrinkles, apartment aesthetic' },
  { id: '032', name: '沙发侧躺动作', prompt: 'lying casually on sofa side, relaxed sleepy body posture, realistic loungewear folds, soft natural lighting' },
  { id: '033', name: '沙发蜷缩动作', prompt: 'curled up naturally on couch, blanket nearby, cozy feminine homewear atmosphere, realistic pajama texture' },
  { id: '034', name: '沙发伸腿动作', prompt: 'lounging on sofa with legs stretched naturally, relaxed shoulders, cozy lifestyle sleepwear photography' },
  { id: '035', name: '沙发托脸动作', prompt: 'resting chin softly on hand while sitting on sofa, sleepy relaxed emotion, soft pajama folds' },
  { id: '036', name: '地毯盘腿动作', prompt: 'cross-legged sitting on carpet floor, oversized pajama naturally draped, cozy apartment lifestyle scene' },
  { id: '037', name: '地毯趴坐动作', prompt: 'casually sitting low on floor with hands behind body, relaxed homewear posture, realistic sleepwear folds' },
  { id: '038', name: '靠墙坐地动作', prompt: 'sitting on floor leaning against wall, knees bent softly, cozy emotional pajama atmosphere' },
  { id: '039', name: '光脚站立动作', prompt: 'standing barefoot naturally indoors, relaxed sleepy posture, realistic pajama drape and folds' },
  { id: '040', name: '光脚行走动作', prompt: 'walking barefoot across bedroom naturally, soft pajama movement, cozy apartment lifestyle aesthetic' },
  { id: '041', name: '晨起拉窗帘动作', prompt: 'opening bedroom curtains naturally, soft sunlight entering room, realistic pajama wrinkles, cinematic morning routine' },
  { id: '042', name: '窗边伸懒腰动作', prompt: 'stretching softly near window, relaxed sleepy body movement, natural pajama folds, cozy feminine energy' },
  { id: '043', name: '窗边低头喝咖啡', prompt: 'holding coffee mug near chest while looking downward, relaxed cozy morning atmosphere, realistic sleepwear pose' },
  { id: '044', name: '窗边发呆动作', prompt: 'looking softly outside window, relaxed shoulders, dreamy apartment mood, natural pajama silhouette' },
  { id: '045', name: '单手拿马克杯动作', prompt: 'holding warm mug casually with one hand, cozy sleepy posture, realistic pajama lifestyle photography' },
  { id: '046', name: '双手捧热饮动作', prompt: 'both hands wrapped around warm drink, oversized sleeves covering wrists slightly, cozy winter pajama mood' },
  { id: '047', name: '厨房料理动作', prompt: 'standing casually in kitchen preparing breakfast, relaxed home posture, realistic pajama drape and movement' },
  { id: '048', name: '开冰箱动作', prompt: 'opening refrigerator naturally, relaxed pajama posture, casual candid lifestyle moment' },
  { id: '049', name: '厨房靠台动作', prompt: 'leaning casually against kitchen counter, coffee nearby, cozy apartment aesthetic, realistic sleepwear folds' },
  { id: '050', name: '早餐桌坐姿', prompt: 'sitting naturally at breakfast table, holding coffee or toast casually, cozy feminine pajama atmosphere' },
  { id: '051', name: '洗手台整理头发动作', prompt: 'standing near sink fixing messy morning hair, relaxed sleepy vibe, realistic pajama wrinkles' },
  { id: '052', name: '镜前刷牙动作', prompt: 'holding toothbrush casually in front of mirror, natural pajama posture, realistic morning routine aesthetic' },
  { id: '053', name: '护肤动作', prompt: 'applying skincare naturally, soft bathroom lighting, cozy feminine sleepwear lifestyle' },
  { id: '054', name: '浴室镜前自拍动作', prompt: 'mirror selfie inspired pose in pajamas, relaxed body angle, cozy influencer homewear aesthetic' },
  { id: '055', name: '单手扶洗手台动作', prompt: 'one hand resting on bathroom sink naturally, relaxed posture, realistic pajama folds' },
  { id: '056', name: '房间整理动作', prompt: 'casually organizing blanket or pillow, natural body movement, cozy realistic pajama atmosphere' },
  { id: '057', name: '单手拿手机坐姿', prompt: 'sitting casually while scrolling phone, relaxed sleepy emotion, realistic homewear folds' },
  { id: '058', name: '边走边看手机动作', prompt: 'walking indoors while looking at phone casually, relaxed pajama movement, lifestyle aesthetic' },
  { id: '059', name: '视频通话动作', prompt: 'holding phone slightly upward as if on video call, soft cozy homewear mood, realistic pajama posture' },
  { id: '060', name: '双手抱猫动作', prompt: 'holding cat naturally while sitting on sofa or bed, cozy feminine apartment atmosphere, realistic pajama styling' },
  { id: '061', name: '双手抱狗动作', prompt: 'hugging small dog casually in pajamas, warm cozy emotional lifestyle photography' },
  { id: '062', name: '单手抱玩偶动作', prompt: 'holding plush toy naturally near chest, cozy youthful sleepwear mood' },
  { id: '063', name: '托腮发呆动作', prompt: 'resting chin on hand while sitting casually, sleepy emotional atmosphere, realistic pajama folds' },
  { id: '064', name: '双手撑脸动作', prompt: 'both hands softly supporting face, oversized sleeves slightly covering hands, cozy cute pajama aesthetic' },
  { id: '065', name: '低头看书动作', prompt: 'reading book naturally while sitting on bed or sofa, relaxed pajama posture, apartment aesthetic' },
  { id: '066', name: '翻书动作', prompt: 'turning pages naturally, relaxed upper body posture, cozy homewear lifestyle scene' },
  { id: '067', name: '耳机听歌动作', prompt: 'wearing headphones casually while sitting on bed, dreamy cozy pajama atmosphere' },
  { id: '068', name: '单手整理被子动作', prompt: 'one hand casually adjusting blanket, natural bedding wrinkles, cozy sleepy home feeling' },
  { id: '069', name: '半睡半醒动作', prompt: 'sleepy relaxed expression, messy hair, oversized pajamas naturally wrinkled, cinematic morning mood' },
  { id: '070', name: '抱膝看窗外动作', prompt: 'hugging knees softly while looking outside window, emotional cozy atmosphere, realistic pajama folds' },
  { id: '071', name: '蜷缩睡姿动作', prompt: 'soft curled sleeping position, blanket partially covering body, cozy feminine bedroom mood' },
  { id: '072', name: '趴床玩手机动作', prompt: 'lying on stomach while using phone casually, legs bent naturally upward, cozy pajama aesthetic' },
  { id: '073', name: '靠窗坐地动作', prompt: 'sitting on floor beside window, soft sunlight, oversized sleepwear draping naturally' },
  { id: '074', name: '半遮脸动作', prompt: 'sleeves or blanket partially covering face, cozy shy sleepy mood, soft feminine pajama atmosphere' },
  { id: '075', name: '双手插睡裤口袋动作', prompt: 'hands casually inside pajama pants pockets, relaxed sleepy standing posture, realistic loungewear styling' },
  { id: '076', name: '回头微笑动作', prompt: 'looking back with soft sleepy smile, natural pajama folds, cozy apartment aesthetic' },
  { id: '077', name: '肩膀滑落动作', prompt: 'one shoulder slightly exposed from oversized pajama top, relaxed cozy homewear feeling' },
  { id: '078', name: '单腿盘坐动作', prompt: 'one leg folded naturally while sitting, relaxed pajama drape, cozy feminine home atmosphere' },
  { id: '079', name: '轻抬脚尖动作', prompt: 'standing casually on tiptoe slightly, playful feminine pajama energy, realistic body balance' },
  { id: '080', name: '被窝喝咖啡动作', prompt: 'sitting inside blanket holding coffee mug, cozy intimate bedroom atmosphere, realistic bedding folds' },
  { id: '081', name: '轻靠床头发呆动作', prompt: 'leaning softly against bed headboard, relaxed sleepy gaze, oversized pajama naturally wrinkled, cozy emotional bedroom atmosphere' },
  { id: '082', name: '双腿悬床动作', prompt: 'sitting on edge of bed with legs hanging naturally, relaxed shoulders, soft morning pajama mood' },
  { id: '083', name: '抱毯坐姿', prompt: 'holding soft blanket around body while sitting, cozy intimate homewear feeling, realistic fabric folds' },
  { id: '084', name: '单手抓被角动作', prompt: 'one hand lightly holding blanket corner, relaxed sleepy posture, realistic bedding texture and folds' },
  { id: '085', name: '双手抓被子动作', prompt: 'both hands holding blanket softly near chest, cozy feminine pajama atmosphere, warm apartment aesthetic' },
  { id: '086', name: '靠窗蜷腿动作', prompt: 'sitting near window with knees softly bent, dreamy natural light, oversized pajamas draping naturally' },
  { id: '087', name: '窗边托腮动作', prompt: 'resting chin on hand near window, sleepy emotional mood, realistic soft pajama wrinkles' },
  { id: '088', name: '窗边盘腿喝咖啡', prompt: 'cross-legged sitting near window holding coffee mug, cozy relaxed homewear atmosphere' },
  { id: '089', name: '晨光照脸动作', prompt: 'soft sunlight hitting face naturally, relaxed sleepy posture, cozy cinematic pajama aesthetic' },
  { id: '090', name: '低头整理裤脚动作', prompt: 'looking downward while adjusting pajama pant leg, realistic fabric bunching, casual homewear movement' },
  { id: '091', name: '伸手拿东西动作', prompt: 'reaching casually toward nearby object, natural upper body extension, realistic pajama folds and movement' },
  { id: '092', name: '开门回头动作', prompt: 'opening bedroom door while looking back softly, relaxed pajama silhouette, cinematic lifestyle scene' },
  { id: '093', name: '手扶门边动作', prompt: 'one hand resting naturally on doorway, cozy sleepy feminine posture, realistic loungewear folds' },
  { id: '094', name: '赤脚踩地动作', prompt: 'bare feet touching soft carpet naturally, relaxed pajama posture, cozy apartment aesthetic' },
  { id: '095', name: '拿毛毯动作', prompt: 'holding folded blanket casually near waist or chest, cozy winter sleepwear mood' },
  { id: '096', name: '抱热水袋动作', prompt: 'holding warm heating pad or plush pillow close to body, cozy emotional pajama atmosphere' },
  { id: '097', name: '靠枕侧坐动作', prompt: 'side seated pose leaning on pillow, relaxed feminine body line, realistic pajama wrinkles' },
  { id: '098', name: '躺沙发看电视动作', prompt: 'lying comfortably on couch watching TV, cozy homewear vibe, realistic relaxed pajama folds' },
  { id: '099', name: '双脚搭沙发动作', prompt: 'legs casually resting on sofa, relaxed lounging posture, oversized pajama naturally draped' },
  { id: '100', name: '单手扶额动作', prompt: 'one hand softly touching forehead, sleepy relaxed expression, cozy realistic pajama styling' },
  { id: '101', name: '双手撑床回头动作', prompt: 'both hands supporting body on bed while looking back toward camera, cozy feminine bedroom atmosphere' },
  { id: '102', name: '被窝探脚动作', prompt: 'blanket covering most body with feet slightly visible, intimate cozy homewear mood' },
  { id: '103', name: '抱枕趴床动作', prompt: 'lying on stomach hugging pillow naturally, relaxed playful pajama energy, realistic bedding folds' },
  { id: '104', name: '床上交叉腿动作', prompt: 'sitting casually on bed with legs crossed, oversized pajama wrinkles naturally formed' },
  { id: '105', name: '坐床边穿拖鞋动作', prompt: 'putting on slippers while sitting on bed edge, natural morning routine aesthetic' },
  { id: '106', name: '单手拉袖口动作', prompt: 'one hand gently pulling pajama sleeve cuff, realistic soft fabric wrinkles, cozy homewear detail pose' },
  { id: '107', name: '双手藏袖动作', prompt: 'hands hidden slightly inside oversized sleeves, cozy cute feminine pajama atmosphere' },
  { id: '108', name: '轻抓领口动作', prompt: 'one hand lightly holding pajama collar area, relaxed sleepy posture, realistic neckline folds' },
  { id: '109', name: '扶肩披毯动作', prompt: 'holding blanket over shoulders naturally, cozy apartment aesthetic, soft emotional pajama scene' },
  { id: '110', name: '手扶腰懒散站姿', prompt: 'one hand resting lazily on waist, relaxed sleepy standing posture, natural pajama drape' },
  { id: '111', name: '打哈欠动作', prompt: 'natural yawning pose, sleepy morning expression, cozy oversized sleepwear atmosphere' },
  { id: '112', name: '擦眼睛动作', prompt: 'one hand rubbing eye naturally, realistic waking-up emotion, cozy pajama morning scene' },
  { id: '113', name: '双手揉头发动作', prompt: 'both hands running through messy morning hair, relaxed sleepy posture, natural pajama folds' },
  { id: '114', name: '抱腿低头动作', prompt: 'hugging legs while lowering head slightly, emotional cozy bedroom atmosphere' },
  { id: '115', name: '被窝蜷缩动作', prompt: 'wrapped up tightly inside blanket, only partial pajamas visible, warm sleepy feminine aesthetic' },
  { id: '116', name: '床边站立发呆动作', prompt: 'standing beside bed naturally, relaxed sleepy body posture, soft apartment lighting' },
  { id: '117', name: '光脚靠墙动作', prompt: 'leaning casually against wall barefoot, oversized pajama folds naturally draped' },
  { id: '118', name: '拿睡眠眼罩动作', prompt: 'holding sleep mask casually near face or forehead, cozy bedtime lifestyle photography' },
  { id: '119', name: '戴眼罩半睡动作', prompt: 'wearing sleep mask pushed upward slightly, sleepy relaxed expression, soft pajama atmosphere' },
  { id: '120', name: '床头灯暖光动作', prompt: 'sitting beside warm bedside lamp lighting, cozy cinematic bedroom atmosphere, realistic pajama folds' },
  { id: '121', name: '夜晚抱枕动作', prompt: 'hugging pillow under warm dim lighting, intimate emotional homewear scene' },
  { id: '122', name: '夜晚坐床动作', prompt: 'sitting quietly on bed at night, soft lamp lighting, cozy pajama silhouette' },
  { id: '123', name: '睡前看手机动作', prompt: 'lying in bed while scrolling phone naturally, realistic bedding folds, relaxed nighttime pajama mood' },
  { id: '124', name: '睡前护肤动作', prompt: 'applying night skincare while wearing pajamas, cozy feminine apartment aesthetic' },
  { id: '125', name: '睡前喝热饮动作', prompt: 'holding warm milk or tea before sleep, relaxed oversized pajama styling, soft nighttime atmosphere' },
  { id: '126', name: '穿拖鞋行走动作', prompt: 'walking casually indoors wearing slippers, natural pajama movement and folds' },
  { id: '127', name: '单手扶床头动作', prompt: 'one hand resting on headboard naturally, relaxed sleepy body posture' },
  { id: '128', name: '双手撑窗台动作', prompt: 'both hands resting lightly on window ledge, cozy morning sunlight, realistic pajama silhouette' },
  { id: '129', name: '半身窝沙发动作', prompt: 'upper body curled softly into sofa corner, blanket nearby, cozy emotional pajama atmosphere' },
  { id: '130', name: '身体陷进床里动作', prompt: 'soft relaxed posture sinking naturally into bed mattress, realistic bedding compression and pajama folds' },
  { id: '131', name: '回头抱毯动作', prompt: 'looking back softly while wrapped in blanket, cozy feminine winter homewear feeling' },
  { id: '132', name: '侧卧看镜头动作', prompt: 'lying on side while softly looking toward camera, realistic pajama wrinkles and bedding texture' },
  { id: '133', name: '床边托腿动作', prompt: 'sitting casually with one knee hugged softly, relaxed sleepy expression, cozy feminine pajama mood' },
  { id: '134', name: '低头闻咖啡动作', prompt: 'looking down toward coffee cup softly, relaxed morning apartment atmosphere' },
  { id: '135', name: '单手扶窗帘动作', prompt: 'one hand lightly touching curtain fabric, natural sunlight entering room, cozy pajama silhouette' },
  { id: '136', name: '房间慢步动作', prompt: 'walking slowly through bedroom naturally, soft pajama movement, realistic lifestyle homewear photography' },
  { id: '137', name: '抱书窝沙发动作', prompt: 'curled up on sofa holding book, oversized pajamas naturally folded, cozy apartment mood' },
  { id: '138', name: '双腿搭床动作', prompt: 'lying casually with legs resting softly across bed, realistic pajama drape and folds' },
  { id: '139', name: '夜晚发呆动作', prompt: 'quiet emotional nighttime pose, warm lamp lighting, relaxed pajama silhouette' },
  { id: '140', name: '被窝露肩动作', prompt: 'blanket softly slipping off shoulder, cozy intimate feminine homewear aesthetic' },
  { id: '141', name: '被窝露腿动作', prompt: 'blanket partially covering body with legs softly visible, cozy feminine sleepwear mood, realistic bedding folds' },
  { id: '142', name: '单手抓床单动作', prompt: 'one hand lightly gripping bedsheet, relaxed sleepy posture, cinematic bedroom atmosphere' },
  { id: '143', name: '双手扶床起身动作', prompt: 'both hands supporting body while getting out of bed naturally, realistic pajama movement and folds' },
  { id: '144', name: '半躺看书动作', prompt: 'half-lying on bed reading book casually, cozy apartment aesthetic, oversized pajama naturally wrinkled' },
  { id: '145', name: '侧躺托脸动作', prompt: 'lying sideways with chin resting on hand, relaxed emotional feminine mood, cozy sleepwear atmosphere' },
  { id: '146', name: '床边弯腰动作', prompt: 'slightly bending forward beside bed naturally, realistic pajama tension and folds around waist' },
  { id: '147', name: '伸脚踩地动作', prompt: 'slowly placing bare feet onto floor beside bed, cinematic morning routine feeling' },
  { id: '148', name: '被窝翻身动作', prompt: 'natural turning movement under blanket, realistic bedding wrinkles, sleepy homewear atmosphere' },
  { id: '149', name: '低头整理被子动作', prompt: 'looking downward while smoothing blanket naturally, relaxed feminine pajama mood' },
  { id: '150', name: '轻靠床头闭眼动作', prompt: 'leaning softly against headboard with eyes closed, calm sleepy emotional atmosphere' },
  { id: '151', name: '床边拿衣服动作', prompt: 'reaching casually toward nearby clothes or robe, realistic upper body movement, cozy apartment vibe' },
  { id: '152', name: '半身窝进被窝动作', prompt: 'upper body tucked inside blanket, cozy intimate sleepwear scene, realistic bedding compression' },
  { id: '153', name: '睡衣外搭开衫动作', prompt: 'wearing cardigan loosely over pajamas, relaxed home layering aesthetic, cozy feminine mood' },
  { id: '154', name: '抱膝坐窗边动作', prompt: 'hugging knees softly while sitting near window, dreamy natural light, emotional cozy atmosphere' },
  { id: '155', name: '单手扶窗低头动作', prompt: 'one hand resting near window frame while looking downward softly, cinematic pajama silhouette' },
  { id: '156', name: '双手托咖啡杯取暖动作', prompt: 'both hands warming around hot mug, oversized sleeves naturally covering wrists, cozy winter sleepwear mood' },
  { id: '157', name: '拿早餐托盘动作', prompt: 'holding breakfast tray casually in pajamas, relaxed home routine aesthetic, realistic lifestyle photography' },
  { id: '158', name: '沙发窝毯动作', prompt: 'wrapped softly in blanket while lounging on sofa, cozy oversized sleepwear styling' },
  { id: '159', name: '光脚踩毛毯动作', prompt: 'bare feet touching soft blanket or carpet naturally, intimate cozy apartment feeling' },
  { id: '160', name: '坐姿弯腰动作', prompt: 'slightly leaning forward while seated naturally, realistic pajama folds around stomach and waist' },
  { id: '161', name: '双手抱腰动作', prompt: 'arms wrapped softly around waist, relaxed emotional sleepy posture, cozy feminine pajama atmosphere' },
  { id: '162', name: '夜晚抱膝坐床动作', prompt: 'sitting quietly on bed at night hugging knees softly, warm bedside lamp lighting, cinematic emotional scene' },
  { id: '163', name: '看向天花板动作', prompt: 'lying naturally while looking upward calmly, oversized pajamas softly wrinkled, relaxed homewear mood' },
  { id: '164', name: '床边托脸发呆动作', prompt: 'resting face softly on hand while sitting beside bed, sleepy apartment atmosphere' },
  { id: '165', name: '手扶肩带动作', prompt: 'one hand lightly touching pajama strap area, relaxed feminine sleepwear posture, cozy intimate mood' },
  { id: '166', name: '单手整理睡裤动作', prompt: 'one hand casually adjusting pajama pants, natural fabric bunching and folds, realistic homewear detail' },
  { id: '167', name: '慢动作走向窗边', prompt: 'slowly walking toward window naturally, soft pajama movement, cinematic morning light' },
  { id: '168', name: '半身裹毯动作', prompt: 'blanket wrapped around upper body softly, cozy emotional sleepwear atmosphere' },
  { id: '169', name: '靠窗闭眼晒太阳动作', prompt: 'standing near window with eyes closed softly, warm sunlight on pajamas, dreamy apartment aesthetic font' },
  { id: '170', name: '沙发伸懒腰动作', prompt: 'stretching casually while sitting on sofa, oversized pajamas naturally folded, cozy relaxed energy' },
  { id: '171', name: '轻靠沙发扶手动作', prompt: 'leaning softly on sofa armrest, relaxed sleepy posture, realistic homewear draping' },
  { id: '172', name: '床边侧坐回头动作', prompt: 'side seated on bed while looking back softly, natural spine twist, cozy pajama silhouette' },
  { id: '173', name: '低头抱咖啡动作', prompt: 'holding coffee cup close to chest while looking downward, warm emotional pajama atmosphere' },
  { id: '174', name: '脚踩椅边动作', prompt: 'one foot resting casually on chair edge, oversized pajamas naturally draped, cozy apartment aesthetic' },
  { id: '175', name: '睡前整理枕头动作', prompt: 'adjusting pillow naturally before sleep, realistic bedding folds, intimate feminine homewear scene' },
  { id: '176', name: '拿遥控器动作', prompt: 'holding remote casually while lounging on sofa, cozy pajama lifestyle mood' },
  { id: '177', name: '床上翻阅杂志动作', prompt: 'reading magazine naturally on bed, relaxed feminine posture, realistic pajama folds' },
  { id: '178', name: '单手撑下巴侧坐动作', prompt: 'side seated pose with chin supported by hand, dreamy emotional apartment atmosphere' },
  { id: '179', name: '卧室门口回头动作', prompt: 'standing near bedroom doorway while looking back softly, cinematic pajama silhouette' },
  { id: '180', name: '双手捂脸动作', prompt: 'both hands softly covering face playfully, oversized sleeves partially hiding hands, cozy cute pajama vibe' },
  { id: '181', name: '被窝探肩动作', prompt: 'shoulder softly visible above blanket, cozy intimate sleepwear atmosphere, realistic bedding texture' },
  { id: '182', name: '夜晚靠窗动作', prompt: 'standing quietly beside window at night, warm ambient lighting, relaxed pajama silhouette' },
  { id: '183', name: '抱毯蜷缩沙发动作', prompt: 'curling up into blanket on couch naturally, cozy winter pajama mood, realistic fabric folds' },
  { id: '184', name: '边走边披毯动作', prompt: 'walking casually indoors with blanket draped over shoulders, cozy cinematic apartment feeling' },
  { id: '185', name: '伸手拿咖啡动作', prompt: 'reaching naturally toward coffee mug nearby, relaxed sleepy movement, realistic pajama wrinkles' },
  { id: '186', name: '轻靠厨房台面动作', prompt: 'leaning softly against kitchen counter in pajamas, relaxed home routine vibe' },
  { id: '187', name: '半身靠门动作', prompt: 'upper body leaning casually against doorway, cozy sleepy feminine atmosphere' },
  { id: '188', name: '单手扶椅背动作', prompt: 'one hand resting lightly on chair back, relaxed pajama posture, realistic apartment aesthetic' },
  { id: '189', name: '床边垂腿动作', prompt: 'sitting on bed edge with legs hanging softly, sleepy relaxed morning mood' },
  { id: '190', name: '闭眼享受阳光动作', prompt: 'eyes closed softly while sunlight hits face naturally, warm cinematic pajama atmosphere' },
  { id: '191', name: '拿牛奶杯动作', prompt: 'holding milk glass casually in pajamas, cozy bedtime routine aesthetic' },
  { id: '192', name: '双手撑膝站姿', prompt: 'both hands resting softly on knees while bending slightly forward, playful sleepy posture' },
  { id: '193', name: '低头闻被子动作', prompt: 'softly leaning into blanket or pillow, cozy emotional feminine homewear feeling' },
  { id: '194', name: '双手抱肩动作', prompt: 'arms wrapped gently around shoulders, cozy intimate winter sleepwear atmosphere' },
  { id: '195', name: '靠床坐地动作', prompt: 'sitting on floor leaning against side of bed, relaxed emotional pajama posture' },
  { id: '196', name: '抬头发呆动作', prompt: 'looking upward dreamily, relaxed body posture, oversized pajamas naturally wrinkled' },
  { id: '197', name: '半躺撑头动作', prompt: 'half-lying pose with one hand supporting head softly, cozy feminine apartment aesthetic' },
  { id: '198', name: '轻扶额头闭眼动作', prompt: 'one hand lightly touching forehead with eyes closed, sleepy emotional morning atmosphere' },
  { id: '199', name: '单手抱枕看镜头动作', prompt: 'holding pillow with one arm while softly looking toward camera, cozy realistic pajama styling' },
  { id: '200', name: '披毯看窗外动作', prompt: 'wrapped in blanket while quietly looking outside window, cinematic emotional homewear scene' },
  { id: '201', name: '半躺看窗外动作', prompt: 'half-lying naturally on bed while looking toward window, soft morning light, cozy emotional pajama atmosphere' },
  { id: '202', name: '单手托头侧卧动作', prompt: 'side lying pose with one hand supporting head softly, relaxed feminine silhouette, realistic pajama folds' },
  { id: '203', name: '双手抱腿窝角落动作', prompt: 'hugging legs while sitting curled in sofa or bed corner, cozy emotional homewear mood' },
  { id: '204', name: '趴床看镜头动作', prompt: 'lying on stomach on bed while looking softly toward camera, relaxed playful pajama energy' },
  { id: '205', name: '被窝里露眼睛动作', prompt: 'partially hidden under blanket with only eyes visible, cozy intimate sleepwear aesthetic' },
  { id: '206', name: '侧坐梳头动作', prompt: 'sitting casually while brushing hair naturally, realistic pajama wrinkles, cozy morning routine scene' },
  { id: '207', name: '双手抓头发动作', prompt: 'both hands loosely gathering hair upward, sleepy relaxed posture, oversized pajamas naturally folded' },
  { id: '208', name: '单手撑腰慵懒动作', prompt: 'one hand resting lazily on waist, relaxed sleepy body posture, soft apartment lighting' },
  { id: '209', name: '双腿搭床头动作', prompt: 'lying casually with legs resting upward near headboard, oversized pajamas draping naturally' },
  { id: '210', name: '低头抱热饮动作', prompt: 'holding warm drink close to chest while lowering head softly, cozy winter pajama mood' },
  { id: '211', name: '靠窗喝热茶动作', prompt: 'standing near window drinking tea naturally, cinematic morning light, relaxed feminine homewear pose' },
  { id: '212', name: '单手摸脖子动作', prompt: 'one hand softly touching neck area, sleepy relaxed expression, realistic pajama neckline folds' },
  { id: '213', name: '轻抓毯边动作', prompt: 'lightly holding edge of blanket near shoulder, cozy intimate apartment atmosphere' },
  { id: '214', name: '被窝托脸动作', prompt: 'resting face softly on hand while inside blanket, warm emotional pajama scene' },
  { id: '215', name: '半躺刷手机动作', prompt: 'half-lying casually while scrolling smartphone, realistic pajama folds and bedding wrinkles' },
  { id: '216', name: '卧室门边站姿', prompt: 'standing naturally beside bedroom doorway, relaxed sleepy posture, oversized pajamas softly draped' },
  { id: '217', name: '双手扶窗动作', prompt: 'both hands resting on window frame naturally, dreamy sunlight atmosphere, realistic sleepwear silhouette' },
  { id: '218', name: '单手扶床沿动作', prompt: 'one hand casually touching edge of bed, relaxed feminine posture, cinematic homewear styling' },
  { id: '219', name: '床边交叉腿坐姿', prompt: 'sitting on edge of bed with legs crossed softly, relaxed shoulders, cozy pajama wrinkles' },
  { id: '220', name: '蜷缩抱毯动作', prompt: 'curled softly inside blanket, emotional cozy feminine atmosphere, realistic bedding compression' },
  { id: '221', name: '单手拿早餐动作', prompt: 'holding toast or small breakfast plate casually, cozy kitchen morning routine aesthetic' },
  { id: '222', name: '厨房煮咖啡动作', prompt: 'making coffee casually in pajamas, realistic lifestyle movement, cozy apartment atmosphere' },
  { id: '223', name: '拉开冰箱拿饮料动作', prompt: 'opening fridge while reaching for drink naturally, relaxed sleepy posture, realistic pajama folds' },
  { id: '224', name: '沙发盖毯动作', prompt: 'blanket softly covering legs while sitting on sofa, cozy homewear lifestyle mood' },
  { id: '225', name: '轻抬肩回头动作', prompt: 'slight shoulder lift while looking back softly, playful feminine pajama energy' },
  { id: '226', name: '半身窝进沙发动作', prompt: 'upper body sinking naturally into sofa cushions, relaxed oversized pajama silhouette' },
  { id: '227', name: '单手撑沙发动作', prompt: 'one hand supporting body on couch casually, relaxed emotional homewear atmosphere' },
  { id: '228', name: '双腿自然蜷缩动作', prompt: 'legs softly curled while lounging naturally, realistic pajama folds and cozy posture' },
  { id: '229', name: '被窝看书动作', prompt: 'reading book while wrapped inside blanket, cinematic nighttime pajama mood' },
  { id: '230', name: '低头玩头发动作', prompt: 'looking downward while softly playing with hair, cozy sleepy feminine aesthetic' },
  { id: '231', name: '手扶锁骨动作', prompt: 'one hand resting softly near collarbone, relaxed intimate pajama mood, realistic neckline detail' },
  { id: '232', name: '单手抓衣摆动作', prompt: 'one hand lightly holding pajama hem, natural fabric tension and folds, realistic homewear detail' },
  { id: '233', name: '双手抱马克杯动作', prompt: 'holding oversized mug with both hands naturally, cozy winter apartment aesthetic' },
  { id: '234', name: '睡前靠墙坐姿', prompt: 'sitting on floor leaning against wall before sleep, relaxed emotional pajama atmosphere' },
  { id: '235', name: '半身裹被动作', prompt: 'upper body wrapped softly in blanket while seated, cozy intimate feminine homewear feeling' },
  { id: '236', name: '床边轻晃腿动作', prompt: 'sitting casually on bed edge while legs swing naturally, playful cozy pajama mood' },
  { id: '237', name: '双手交叠抱腿动作', prompt: 'hands folded softly around knees, sleepy emotional apartment aesthetic' },
  { id: '238', name: '闭眼抱咖啡动作', prompt: 'eyes softly closed while holding warm coffee near chest, cinematic cozy homewear mood' },
  { id: '239', name: '沙发伸腿闭眼动作', prompt: 'lounging on sofa with legs stretched out and eyes closed softly, realistic relaxed pajama styling' },
  { id: '240', name: '半身低头靠窗动作', prompt: 'upper body leaning softly near window while looking downward, dreamy sunlight atmosphere' },
  { id: '241', name: '披毯站窗边动作', prompt: 'standing near window wrapped in blanket, cozy winter pajama aesthetic, cinematic apartment lighting' },
  { id: '242', name: '单手扶头坐姿', prompt: 'one hand resting on side of head naturally while seated, sleepy relaxed feminine posture' },
  { id: '243', name: '被窝探手动作', prompt: 'one hand reaching softly outside blanket, cozy intimate bedding atmosphere' },
  { id: '244', name: '双手撑床仰头动作', prompt: 'both hands supporting body behind while face tilts upward softly, relaxed emotional pajama mood' },
  { id: '245', name: '卧室镜子整理睡衣动作', prompt: 'adjusting pajama top naturally in bedroom mirror, influencer-inspired cozy lifestyle aesthetic' },
  { id: '246', name: '沙发看电视吃零食动作', prompt: 'lounging casually while holding snack bowl, cozy realistic apartment sleepwear scene' },
  { id: '247', name: '光脚踩窗边动作', prompt: 'standing barefoot near window naturally, warm morning sunlight, relaxed pajama silhouette' },
  { id: '248', name: '单手抱玩偶发呆动作', prompt: 'holding plush toy loosely while staring softly ahead, emotional cozy pajama atmosphere' },
  { id: '249', name: '双手环抱自己动作', prompt: 'arms wrapped around body gently, warm intimate winter homewear feeling' },
  { id: '250', name: '床边闭眼静坐动作', prompt: 'quiet seated pose on bed with eyes closed softly, cinematic emotional pajama scene' }
];
