export interface WomensFashionPose {
  id: string;
  name: string;
  prompt: string;
}

const WOMENS_FASHION_FRAME =
  'generic womenswear fashion lookbook framing, clean commercial fashion posture, garment shape and styling clearly readable, natural feminine proportions, realistic fabric drape, professional ecommerce editorial pose, no stiff mannequin posture';

const WOMENS_FASHION_POSE_PROMPTS = [
  'weight shifted onto one leg, relaxed fashion posture',
  'legs crossed naturally, editorial elegance',
  'one foot slightly forward, elongated silhouette',
  'three-quarter body angle',
  'body rotated slightly, showing garment shape',
  'front-facing luxury lookbook pose',
  'arms relaxed beside body',
  'one hand inside pocket naturally',
  'both hands in pockets, relaxed confidence',
  'one hand resting on waist',
  'hands on waist, editorial fashion stance',
  'arms crossed softly',
  'one hand touching opposite arm',
  'touching collarbone naturally',
  'touching neck softly',
  'hair adjustment movement',
  'lifting hair naturally',
  'hair sweep motion',
  'hair moving in wind',
  'touching hair near ear',
  'holding handbag naturally',
  'holding handbag in front',
  'bag tucked under arm',
  'bag hanging beside body',
  'switching handbag naturally',
  'holding bag strap casually',
  'holding straps with both hands',
  'holding hem softly',
  'showing garment drape',
  'adjusting sleeve naturally',
  'touching collar detail',
  'adjusting blazer naturally',
  'touching wall lightly',
  'leaning against wall',
  'one shoulder touching wall',
  'back against wall',
  'leaning against architectural column',
  'leaning against doorway',
  'one hand resting on railing',
  'both hands resting naturally',
  'looking downward',
  'looking into distance',
  'eyes closed naturally',
  'head slightly raised',
  'looking over shoulder',
  'soft smile over shoulder',
  'half-body rotation',
  'turning naturally',
  'back facing camera, head turned',
  'dress moving during turn',
  'slow confident walk',
  'purposeful city stride',
  'walking while looking back',
  'walking with lowered gaze',
  'walking toward horizon',
  'walking with hands in pockets',
  'holding handbag while walking',
  'garment moving naturally',
  'crossing street naturally',
  'turning city corner',
  'sitting with hands on knees',
  'legs crossed while seated',
  'looking away while seated',
  'looking downward seated',
  'holding handbag seated',
  'one arm supporting body',
  'sitting on stairs naturally',
  'relaxed bench posture',
  'leaning against chair',
  'extended leg composition',
  'standing before architecture',
  'standing near window',
  'natural sunlight pose',
  'shadow composition',
  'minimal editorial composition',
  'architectural leading lines',
  'street style candid moment',
  'fashion week candid',
  'standing naturally while waiting',
  'purposeful movement',
  'coat styling pose',
  'coat draped over shoulders',
  'holding sunglasses',
  'adjusting sunglasses',
  'holding coffee naturally',
  'holding cup with both hands',
  'holding smartphone casually',
  'looking at phone',
  'holding camera casually',
  'looking into storefront',
  'standing beneath archway',
  'corridor composition',
  'dramatic light contrast',
  'backlit editorial pose',
  'fabric movement highlight',
  'coat movement shot',
  'hands behind body',
  'one hand behind back',
  'symmetrical composition',
  'strong editorial hero pose, luxury fashion campaign aesthetic',
  'one shoulder dropped naturally',
  'shoulders slightly tilted',
  'hips shifted to one side',
  'body leaning forward slightly',
  'body leaning backward slightly',
  'torso twisted subtly',
  'one knee bent softly',
  'both knees relaxed',
  'one leg crossing in front',
  'one leg stepping backward',
  'standing on tiptoe slightly',
  'one heel lifted',
  'weight on back leg',
  'weight on front leg',
  'one foot against wall',
  'ankles crossed naturally',
  'sitting with legs extended',
  'sitting with knees together',
  'sitting sideways on chair',
  'sitting on stair edge',
  'looking down toward hands',
  'looking toward street',
  'looking through window',
  'looking upward softly',
  'looking over shoulder',
  'looking across body line',
  'looking at handbag',
  'looking at clothing details',
  'eyes closed naturally',
  'eyes partially closed',
  'chin slightly raised',
  'chin slightly lowered',
  'head tilted left',
  'head tilted right',
  'neck elongated upward',
  'hair covering one eye',
  'wind blowing hair backward',
  'wind blowing hair across face',
  'hair tucked behind ear',
  'hair swept with fingers',
  'one hand touching cheek',
  'one hand touching chin',
  'one hand touching jawline',
  'one hand touching collarbone',
  'one hand touching shoulder',
  'one hand touching upper arm',
  'one hand holding opposite wrist',
  'fingers hooked in pocket',
  'hands loosely clasped',
  'one hand behind neck',
  'both hands behind back',
  'arms crossed softly',
  'one hand lifting skirt hem',
  'one hand adjusting dress strap',
  'one hand adjusting blazer lapel',
  'one hand adjusting sunglasses',
  'one hand adjusting sleeve',
  'one hand adjusting cuff',
  'one hand adjusting belt',
  'one hand adjusting handbag strap',
  'clutch held under arm',
  'bag hanging from fingertips',
  'bag resting against hip',
  'bag carried behind body',
  'bag held in front with both hands',
  'bag resting on shoulder',
  'oversized tote hanging naturally',
  'hand inside coat pocket',
  'hands inside trouser pockets',
  'one hand inside dress pocket',
  'walking toward camera',
  'walking away from camera',
  'walking diagonally',
  'walking along wall',
  'walking through doorway',
  'walking across street',
  'walking beside building',
  'walking into sunlight',
  'walking through shadow',
  'walking while turning',
  'stopping mid-stride',
  'looking back while walking',
  'crossing legs while walking',
  'dress flowing behind body',
  'coat moving with stride',
  'standing beneath archway',
  'standing inside corridor',
  'standing beside column',
  'standing beside window',
  'standing beside doorway',
  'leaning against railing',
  'leaning against column',
  'leaning against doorway',
  'leaning against textured wall',
  'leaning against storefront',
  'touching architectural surface',
  'resting hand on railing',
  'standing in sunlight patch',
  'standing in geometric shadow',
  'standing beneath balcony shadow',
  'wind lifting dress hem',
  'wind lifting coat edge',
  'wind lifting loose hair',
  'fabric movement in motion',
  'turning with dress movement',
  'looking away thoughtfully',
  'quiet luxury expression',
  'minimal emotion editorial mood',
  'fashion week candid mood',
  'street style confidence',
  'soft romantic mood',
  'strong editorial attitude',
  'relaxed european elegance',
  'effortless city woman mood',
  'sophisticated luxury energy',
  'neutral runway expression',
  'Vogue editorial attitude',
  "Harper's Bazaar mood",
  'COS campaign mood',
  'Massimo Dutti aesthetic',
  'The Row inspired posture',
  'Toteme inspired posture',
  'Zara Studio styling',
  'standing beneath dramatic sunlight',
  'standing beneath soft diffused light',
  'standing beside reflective glass',
  'standing near textured concrete',
  'standing beside stone architecture',
  'standing beneath large doorway',
  'standing within architectural frame',
  'standing centered in composition',
  'standing off-center composition',
  'large negative space composition',
  'symmetrical composition',
  'asymmetrical composition',
  'long vertical silhouette composition',
  'wide architectural composition',
  'hero fashion campaign pose',
  'luxury lookbook hero shot',
  'fashion week arrival pose',
  'fashion editor street pose',
  'designer showroom pose',
  'luxury hotel entrance pose',
  'European city luxury pose',
  'modern woman campaign pose',
  'premium editorial standing pose',
  'elevated minimalist pose',
  'architectural fashion pose',
  'luxury magazine cover pose',
  'high-end fashion campaign hero pose',
];

export const WOMENS_FASHION_POSES: WomensFashionPose[] = WOMENS_FASHION_POSE_PROMPTS.map((prompt, index) => {
  const id = String(index + 1).padStart(3, '0');
  return {
    id,
    name: `Womens Fashion ${id}`,
    prompt: `${prompt}, ${WOMENS_FASHION_FRAME}`,
  };
});
