export interface Y2KPose {
  id: string;
  name: string;
  prompt: string;
}

const Y2K_FRAME =
  'Y2K high-fashion editorial pose, contemporary designer lookbook attitude, elongated silhouette, asymmetric body line, low-rise denim or trouser campaign energy, confident expression, clothing remains clearly visible, product fit and silhouette readable, realistic fashion model posture';

const withFrame = (prompt: string) => `${prompt}, ${Y2K_FRAME}`;

export const Y2K_POSES: Y2KPose[] = [
  { id: '001', name: 'body leaning diagonally forward', prompt: withFrame('body leaning diagonally forward') },
  { id: '002', name: 'body leaning diagonally backward', prompt: withFrame('body leaning diagonally backward') },
  { id: '003', name: 'shoulders tilted asymmetrically', prompt: withFrame('shoulders tilted asymmetrically') },
  { id: '004', name: 'hips shifted off-center', prompt: withFrame('hips shifted off-center') },
  { id: '005', name: 'one shoulder raised', prompt: withFrame('one shoulder raised') },
  { id: '006', name: 'one shoulder dropped', prompt: withFrame('one shoulder dropped') },
  { id: '007', name: 'torso twisted slightly', prompt: withFrame('torso twisted slightly') },
  { id: '008', name: 'exaggerated three-quarter stance', prompt: withFrame('exaggerated three-quarter stance') },
  { id: '009', name: 'weight entirely on one leg', prompt: withFrame('weight entirely on one leg') },
  { id: '010', name: 'relaxed slouched posture', prompt: withFrame('relaxed slouched posture') },
  { id: '011', name: 'one knee bent inward', prompt: withFrame('one knee bent inward') },
  { id: '012', name: 'one leg crossing over another', prompt: withFrame('one leg crossing over another') },
  { id: 'T01', name: 'trouser emphasis pose', prompt: withFrame('one hand in pocket, hips pushed slightly forward, relaxed shoulders, trouser emphasis pose') },
  { id: 'T02', name: 'denim emphasis pose', prompt: withFrame('both hands in pockets, legs apart, editorial stare, denim emphasis pose') },
  { id: 'T03', name: 'wide leg emphasis pose', prompt: withFrame('one leg forward, showing fabric volume, wide leg emphasis pose') },
  { id: 'T04', name: 'cargo pants emphasis pose', prompt: withFrame('hands behind body, pants become visual focus, cargo pants emphasis pose') },
  { id: 'T05', name: 'low waist emphasis pose', prompt: withFrame('thumbs hooked into waistband, low waist emphasis pose') },
  { id: 'T06', name: 'straight leg emphasis pose', prompt: withFrame('feet parallel, standing still, straight leg emphasis pose') },
  { id: 'T07', name: 'fashion denim pose', prompt: withFrame('body leaning diagonally, one foot forward, fashion denim pose') },
  { id: 'T08', name: 'oversized trousers pose', prompt: withFrame('shoulders relaxed, legs wide apart, oversized trousers pose') },
  { id: 'T09', name: 'y2k menswear pose', prompt: withFrame('chin forward, hands inside pockets, Y2K menswear pose') },
  { id: 'T10', name: 'designer denim campaign pose', prompt: withFrame('torso twisted, lower body facing forward, designer denim campaign pose') },
  { id: 'T11', name: 'luxury trousers campaign pose', prompt: withFrame('one hand behind neck, weight on one leg, luxury trousers campaign pose') },
  { id: 'T12', name: 'runway denim stance', prompt: withFrame('crossed feet, elongated silhouette, runway denim stance') },
  { id: 'T13', name: 'avant-garde trouser pose', prompt: withFrame('asymmetrical body line, avant-garde trouser pose') },
  { id: 'T14', name: 'fashion week denim pose', prompt: withFrame('frozen mid-step, fashion week denim pose') },
  { id: 'T15', name: 'editorial jeans campaign pose', prompt: withFrame('leaning slightly backward, hands in pockets, editorial jeans campaign pose') },
  { id: '013', name: 'feet positioned asymmetrically', prompt: withFrame('feet positioned asymmetrically') },
  { id: '014', name: 'narrow stance fashion pose', prompt: withFrame('narrow stance fashion pose') },
  { id: '015', name: 'wide stance editorial pose', prompt: withFrame('wide stance editorial pose') },
  { id: '016', name: 'one foot pointed outward', prompt: withFrame('one foot pointed outward') },
  { id: '017', name: 'one heel lifted slightly', prompt: withFrame('one heel lifted slightly') },
  { id: '018', name: 'one leg extended forward', prompt: withFrame('one leg extended forward') },
  { id: '019', name: 'one leg extended sideways', prompt: withFrame('one leg extended sideways') },
  { id: '020', name: 'body curved into S-shape', prompt: withFrame('body curved into S-shape') },
  { id: '021', name: 'hands deep in pockets', prompt: withFrame('hands deep in pockets') },
  { id: '022', name: 'thumbs hooked into waistband', prompt: withFrame('thumbs hooked into waistband') },
  { id: '023', name: 'one hand inside pocket', prompt: withFrame('one hand inside pocket') },
  { id: '024', name: 'both hands behind body', prompt: withFrame('both hands behind body') },
  { id: '025', name: 'one hand behind neck', prompt: withFrame('one hand behind neck') },
  { id: '026', name: 'one hand touching jawline', prompt: withFrame('one hand touching jawline') },
  { id: '027', name: 'one hand touching cheek', prompt: withFrame('one hand touching cheek') },
  { id: '028', name: 'one hand touching collar', prompt: withFrame('one hand touching collar') },
  { id: '029', name: 'one hand touching chest', prompt: withFrame('one hand touching chest') },
  { id: '030', name: 'one hand holding opposite arm', prompt: withFrame('one hand holding opposite arm') },
  { id: '031', name: 'arms crossed loosely', prompt: withFrame('arms crossed loosely') },
  { id: '032', name: 'one arm hanging dramatically', prompt: withFrame('one arm hanging dramatically') },
  { id: '033', name: 'one elbow lifted outward', prompt: withFrame('one elbow lifted outward') },
  { id: '034', name: 'hand partially hidden inside sleeve', prompt: withFrame('hand partially hidden inside sleeve') },
  { id: '035', name: 'one hand gripping waistband', prompt: withFrame('one hand gripping waistband') },
  { id: '036', name: 'fingers hooked into belt loop', prompt: withFrame('fingers hooked into belt loop') },
  { id: '037', name: 'hand resting inside jacket opening', prompt: withFrame('hand resting inside jacket opening') },
  { id: '038', name: 'hand tucked behind hip', prompt: withFrame('hand tucked behind hip') },
  { id: '039', name: 'holding bag low beside body', prompt: withFrame('holding bag low beside body') },
  { id: '040', name: 'holding bag suspended in front', prompt: withFrame('holding bag suspended in front') },
  { id: '041', name: 'head tilted downward', prompt: withFrame('head tilted downward') },
  { id: '042', name: 'head tilted upward', prompt: withFrame('head tilted upward') },
  { id: '043', name: 'looking through eyebrows', prompt: withFrame('looking through eyebrows') },
  { id: '044', name: 'direct intense eye contact', prompt: withFrame('direct intense eye contact') },
  { id: '045', name: 'looking past camera', prompt: withFrame('looking past camera') },
  { id: '046', name: 'eyes half closed', prompt: withFrame('eyes half closed') },
  { id: '047', name: 'expressionless editorial stare', prompt: withFrame('expressionless editorial stare') },
  { id: '048', name: 'slightly parted lips', prompt: withFrame('slightly parted lips') },
  { id: '049', name: 'chin pushed forward', prompt: withFrame('chin pushed forward') },
  { id: '050', name: 'chin tucked slightly', prompt: withFrame('chin tucked slightly') },
  { id: '051', name: 'standing completely still', prompt: withFrame('standing completely still') },
  { id: '052', name: 'frozen mid-step', prompt: withFrame('frozen mid-step') },
  { id: '053', name: 'paused during walk', prompt: withFrame('paused during walk') },
  { id: '054', name: 'slow runway walk', prompt: withFrame('slow runway walk') },
  { id: '055', name: 'turning during stride', prompt: withFrame('turning during stride') },
  { id: '056', name: 'crossing legs while walking', prompt: withFrame('crossing legs while walking') },
  { id: '057', name: 'oversized step forward', prompt: withFrame('oversized step forward') },
  { id: '058', name: 'walking directly toward camera', prompt: withFrame('walking directly toward camera') },
  { id: '059', name: 'walking away then looking back', prompt: withFrame('walking away then looking back') },
  { id: '060', name: 'leaning into movement', prompt: withFrame('leaning into movement') },
  { id: '061', name: 'shoulder-first walking pose', prompt: withFrame('shoulder-first walking pose') },
  { id: '062', name: 'standing against invisible wall', prompt: withFrame('standing against invisible wall') },
  { id: '063', name: 'body pressed lightly against wall', prompt: withFrame('body pressed lightly against wall') },
  { id: '064', name: 'one shoulder touching wall', prompt: withFrame('one shoulder touching wall') },
  { id: '065', name: 'back against wall', prompt: withFrame('back against wall') },
  { id: '066', name: 'leaning into corner', prompt: withFrame('leaning into corner') },
  { id: '067', name: 'standing beneath architectural frame', prompt: withFrame('standing beneath architectural frame') },
  { id: '068', name: 'standing between columns', prompt: withFrame('standing between columns') },
  { id: '069', name: 'standing in doorway', prompt: withFrame('standing in doorway') },
  { id: '070', name: 'standing in center composition', prompt: withFrame('standing in center composition') },
  { id: '071', name: 'asymmetrical composition pose', prompt: withFrame('asymmetrical composition pose') },
  { id: '072', name: 'one arm raised overhead', prompt: withFrame('one arm raised overhead') },
  { id: '073', name: 'elbow resting on raised knee', prompt: withFrame('elbow resting on raised knee') },
  { id: '074', name: 'hand touching sunglasses', prompt: withFrame('hand touching sunglasses') },
  { id: '075', name: 'adjusting eyewear', prompt: withFrame('adjusting eyewear') },
  { id: '076', name: 'removing sunglasses slowly', prompt: withFrame('removing sunglasses slowly') },
  { id: '077', name: 'holding necklace', prompt: withFrame('holding necklace') },
  { id: '078', name: 'touching earring', prompt: withFrame('touching earring') },
  { id: '079', name: 'pulling shirt hem slightly', prompt: withFrame('pulling shirt hem slightly') },
  { id: '080', name: 'adjusting waistband naturally', prompt: withFrame('adjusting waistband naturally') },
  { id: '081', name: 'jacket slipping off shoulder', prompt: withFrame('jacket slipping off shoulder') },
  { id: '082', name: 'oversized sleeve covering hand', prompt: withFrame('oversized sleeve covering hand') },
  { id: '083', name: 'garment draped dramatically', prompt: withFrame('garment draped dramatically') },
  { id: '084', name: 'fabric stretched by movement', prompt: withFrame('fabric stretched by movement') },
  { id: '085', name: 'exposing shoulder line', prompt: withFrame('exposing shoulder line') },
  { id: '086', name: 'layering-focused pose', prompt: withFrame('layering-focused pose') },
  { id: '087', name: 'emphasizing silhouette', prompt: withFrame('emphasizing silhouette') },
  { id: '088', name: 'emphasizing trouser volume', prompt: withFrame('emphasizing trouser volume') },
  { id: '089', name: 'emphasizing oversized proportions', prompt: withFrame('emphasizing oversized proportions') },
  { id: '090', name: 'emphasizing narrow upper body', prompt: withFrame('emphasizing narrow upper body') },
  { id: '091', name: 'standing with legs extremely long', prompt: withFrame('standing with legs extremely long') },
  { id: '092', name: 'fashion campaign hero pose', prompt: withFrame('fashion campaign hero pose') },
  { id: '093', name: 'diesel-inspired attitude pose', prompt: withFrame('Diesel-inspired attitude pose, rebellious denim campaign posture') },
  { id: '094', name: 'acne studios inspired pose', prompt: withFrame('Acne Studios inspired pose, minimal offbeat designer lookbook posture') },
  { id: '095', name: 'zara studio editorial pose', prompt: withFrame('Zara studio editorial pose, clean commercial fashion posture') },
  { id: '096', name: 'luxury campaign posture', prompt: withFrame('luxury campaign posture') },
  { id: '097', name: 'avant-garde standing pose', prompt: withFrame('avant-garde standing pose') },
  { id: '098', name: 'runway backstage pose', prompt: withFrame('runway backstage pose') },
  { id: '099', name: 'contemporary designer lookbook pose', prompt: withFrame('contemporary designer lookbook pose') },
  { id: '100', name: 'high-fashion hero pose', prompt: withFrame('high-fashion hero pose') },
];
